### PR TITLE
Allow to specify EntityManager container key

### PR DESCRIPTION
**Pull request by svycka**
sometimes the hardcoded name is not what you want :) also this will allow using different EntityManager's not just default one when needed

### CODE REVIEW

**Comment by Naktibalda** [comment]
Please document this new configuration setting in the docblock above the class.

**Comment by svycka** [comment]
I am not sure how to describe it :D if someone has better idea I am open for suggestions

**Comment by DavertMik** [comment]
This patch looks good but I'd rather call the config option `service_name`

**Comment by svycka** [comment]
I can rename but don't you think service is too generic? maybe then
ormservice or something.

On Feb 17, 2018 4:53 AM, "Michael Bodnarchuk" <notifications@github.com>
wrote:

This patch looks good but I'd rather call the config option service_name

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Codeception/Codeception/pull/4798#issuecomment-366410792>,
or mute the thread

**Comment by DavertMik** [comment]
ok, please make it `orm_service`
Sorry for delay in reply )

**Comment by DavertMik** [comment]
Thanks for reminding me of this PR! 
I really missed it was updated

**Pull request merged**
