### PR TITLE
Merge 2.1 to 2.2

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by stipsan** [comment]
Is the failing WebDriver test on semaphore transient?

**Comment by Naktibalda** [comment]
@DavertMik Could you rerun semaphore build?

**Comment by DavertMik** [comment]
Yes, sorry for delay

**Comment by DavertMik** [comment]
Please merge after https://github.com/Codeception/Codeception/pull/3227 is merged first.

**Pull request merged**
