### PR TITLE
TestMailer now stores messages in the connector.

### PR DESCRIPTION
**Pull request by SamMousa**
Have tested the fix against the test provided here: https://github.com/Codeception/yii2-tests/pull/3

### CODE REVIEW

**Comment by SamMousa** [comment]
@Slamdunk what do you think of this solution?
Instead of trying to change things for the mailer I have altered sending behavior to push messages to the connector (which is reset between tests but not between requests).
This way any other code that expects the mailer to be recreated would still work properly.

**Comment by Slamdunk** [comment]
That's ok for me.

One thing: please provide a manual API to reset the sent-email container (aka the array) so it would be possible to do multiple checks in the same test without manually saving-and-diffing the already sent emails.

**Comment by SamMousa** [comment]
I'm not gonna do that in this PR; I don't think it's a common use case. If needed you can always do it without diffing.
Also, we already have `grabLastSentEmail()` which gives you the last one.

**Comment by SamMousa** [comment]
Closed & reopened to restart Travis

**Comment by DavertMik** [comment]
:+1:

**Pull request merged**
