### PR TITLE
Wrong failed step

### PR DESCRIPTION
**Pull request by eXorus**
Hello,

Context: In one cest file with three tests (1 success and 2 failed)

Actual result: 
```
There were 2 failures:

  ---------
  1) PartialFailedCest: Test case two
   Test  tests/scenario/PartialFailedCest.php:testCaseTwo
   Step  See file found "testcasethree.txt"                  <==== bug here
   Fail  File "testcasetwo.txt" not found at ""

  Scenario Steps:

   2. $I->seeFileFound("testcasetwo.txt") at tests/scenario/PartialFailedCest.php:14
   1. $I->amInPath(".") at tests/scenario/PartialFailedCest.php:13


  ---------
  2) PartialFailedCest: Test case three
   Test  tests/scenario/PartialFailedCest.php:testCaseThree
   Step  See file found "testcasethree.txt"
   Fail  File "testcasethree.txt" not found at ""

  Scenario Steps:

   2. $I->seeFileFound("testcasethree.txt") at tests/scenario/PartialFailedCest.php:20
   1. $I->amInPath(".") at tests/scenario/PartialFailedCest.php:19


  FAILURES!
  Tests: 3, Assertions: 3, Failures: 2.
```

Expected result: 
```
There were 2 failures:

  ---------
  1) PartialFailedCest: Test case two
   Test  tests/scenario/PartialFailedCest.php:testCaseTwo
   Step  See file found "testcasetwo.txt"
   Fail  File "testcasetwo.txt" not found at ""

  Scenario Steps:

   2. $I->seeFileFound("testcasetwo.txt") at tests/scenario/PartialFailedCest.php:14
   1. $I->amInPath(".") at tests/scenario/PartialFailedCest.php:13


  ---------
  2) PartialFailedCest: Test case three
   Test  tests/scenario/PartialFailedCest.php:testCaseThree
   Step  See file found "testcasethree.txt"
   Fail  File "testcasethree.txt" not found at ""

  Scenario Steps:

   2. $I->seeFileFound("testcasethree.txt") at tests/scenario/PartialFailedCest.php:20
   1. $I->amInPath(".") at tests/scenario/PartialFailedCest.php:19


  FAILURES!
  Tests: 3, Assertions: 3, Failures: 2.
```

Fix this previous PR #4607

### CODE REVIEW

**Comment by eXorus** [comment]
@DavertMik I did the fix, it's working in local but I don't understand why not here. There is no specific code for PHP7 so I don't understand why PHP5 is different.

The issue was that `$this->failedStep` is always the last fail step so I duplicate how `$this->failedStep` works. The fix is to have an array to store all the failed steps.

**Comment by Naktibalda** [comment]
```
Failed asserting that ' ...
Tests: 3, Assertions: 1, Failures: 2.' contains "Tests: 3, Assertions: 3, Failures: 2."
```

My guess is that this issue is caused by different versions of PhpUnit. Probably assertion counting was fixed in PhpUnit 6.

**Comment by eXorus** [comment]
I don't like what I did but I removed the test about assertions.

**Comment by DavertMik** [comment]
Thanks, looks like a very clean solution!

**Pull request merged**
