### PR TITLE
Fix doctrine issues after first request is made.

### PR DESCRIPTION
**Pull request by AlexStansfield**
Related to #2025 

I found this change fixed all the problems I was having when using doctrine to create data in a transaction.

Unsure if it's the right solution, but means my tests now work.

### CODE REVIEW

**Comment by AlexStansfield** [comment]
Any chance any one has had a chance to look at this? I don't know if it's the right solution, but it works for us. It would be great to get this bug fixed so we can reliably run our tests without needing to patch codeception.

**Comment by DavertMik** [comment]
If it works for you and tests pass why not to merge then )

**Comment by AlexStansfield** [comment]
Haha ok, I don't claim to know anywhere near enough about the internals of the symfony kernel but if it doesn't break anyone else's tests then I'm happy :grinning:

**Comment by vyarmolenko** [comment]
The solution to clone kernel between requests causes memory leak in functional tests. It can be seen on tests with multiple requests and/or multiple tests in a suite.

I had 'out of memory' errors when ran my test. I changed the code of Lib/Connector/Symfony2.php to its previous version and it works now.

In relation to [https://github.com/Codeception/Codeception/issues/2025]:
In it's current implementation when 'cleanup: true' codeception initializes Doctrine transaction after it creates Symfony2 web client. It may be the cause of problems with the first transaction related routines.
In my test I needed to run different requests against the same db so I implemented a helper method  (mostly from codeception sources). It first rolls back codeception's transaction and initializes its own transaction which is being rolled back between requests:
```php
   /*
     *  Rollback codeception's or any other external transaction(s) and set own  
     */
    public function prepareDatabase($isTransactional = true)
    {
        while ($this->em->getConnection()->isTransactionActive()) {
            try {
                $this->em->getConnection()->rollback();
            } catch (\PDOException $e) {
            }
        }
        $em = $this->em;
        $reflectedEm = new \ReflectionClass($em);
        if ($reflectedEm->hasProperty(' repositories')) {
            $property = $reflectedEm->getProperty('repositories');
            $property->setAccessible(true);
            $property->setValue($em, []);
        }
        $this->em->clear();
        if ($isTransactional) {
            $this->em->getConnection()->beginTransaction();
        }
    }
```

**Comment by AlexStansfield** [comment]
Would changing
```
$this->kernel = clone $this->kernel;
```
to 
```
$tmpKernel = $this->kernel;
$this->kernel = clone $tmpKernel;
unset($tmpKernel);
```
have enabled php to garbage collect when it needs the memory?  

I will revert the change here to see if our tests run successful (and this was fixed else where) or if the initial problem reappears.

**Comment by AlexStansfield** [comment]
Just reread you comment, and will look into what you think might be causing the transaction issue

**Comment by raistlin** [comment]
@vyarmolenko Could you prepare a pull request with your proposed solution?

**Pull request merged**
