### PR TITLE
Preload tests before checking environments; fixes #2032

### LINKED ISSUE #2032: $scenario->env('firefox'); doesn't work
I'm trying to use http://codeception.com/docs/07-AdvancedUsage#Environments
block "For Cept you should use $scenario->env():"
But it doesn't work for me. I saw the same problem on  phptest club.
http://phptest.club/t/environment-help-with-cept/384
Running from comand line with --env firefox works good.

### PR DESCRIPTION
**Pull request by splinter89**
It is aimed to fix #2032. I have only tested it locally and looks like it works.

### CODE REVIEW

**Comment by gunfrank** [comment]
https://github.com/Codeception/Codeception/issues/2032#issuecomment-131000779

**Comment by gunfrank** [comment]
http://phptest.club/t/environment-help-with-cept/384/9 - check the conversation here.

The suggested fix seems to work, just not as I expected. Do excuse me for the misunderstanding.

**Comment by DavertMik** [comment]
Oh, thanks! That was a smart fix to really stupid bug. Merging that!
@splinter89 great to see you on board again )

**Comment by DavertMik** [comment]
I will do a test for that

**Pull request merged**
