### PR TITLE
Turn off colors in Windows console by default

### PR DESCRIPTION
**Pull request by kusnir**

### CODE REVIEW

**Comment by kusnir** [comment]
It is useful for using Codeception in console mode in Windows environment.

**Comment by kusnir** [comment]
OK. Anyway there should by way to set default value so I changed it to use setting from config.

**Comment by DavertMik** [comment]
This fix applies only for interactive console. All other commands especially `run` won't be affected by this change. @kusnir is that what you are actually want to achieve?

**Comment by samdark** [comment]
I think it should be applied to all console output.

**Comment by kusnir** [comment]
I want just FIX output in interactive console (which I run in console without colors support) because only there you can not change default settings by configuration.

I checked it and I recommend:
- remove adding 'colors' settings from Codeception/Command/Bootstrap.php - for using auto default value
- to Codeception/Codecept.php and Codeception/Configuration.php add mentioned detection of colors support

**Comment by samdark** [comment]
Removing isn't a good idea but making it autodetect by default is good.

**Comment by kusnir** [comment]
remove adding 'colors' ... = remove from generated codeception.yml file, so the colors settings will not be in config file by default

**Comment by samdark** [comment]
Yes. Still, ability to configure it explicitly should remain.

**Comment by enumag** [comment]
I'm not quite sure why but somehow colors work for me on windows. So they should not be auto-disabled.

**Pull request closed without merging**
