### PR TITLE
rebased feature-get-internal-domains

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by Naktibalda** [comment]
#2396
I tried `git rebase 2.1` on this branch.
Have I done the right thing?
What should I do next? `git push -f upstream feature-get-internal-domains` ?

**Comment by DavertMik** [comment]
Did you try to squash commits? 
Probably you did something wrong as there are too much commits here...

This is how I squash them http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by janhenkgerritsen** [comment]
I think a rebase will be difficult because the 2.1 branch has been merged into the feature-get-internal-domains branch before, and there was work done on this branch before and after these merges. I think the easiest solution will be to just merge the feature branch into 2.1.

Another option is to just copy/paste the changes into another branch and merge that into the 2.1 branch. The changes for this feature are pretty isolated, so that should not be too much work. This approach has the benefit that we can group the commits of the changes for this feature together.

What do you guys think?

**Comment by Naktibalda** [comment]
@DavertMik Majority of commits in this PR are commits made in 2.1 branch in the last few months.

**Comment by janhenkgerritsen** [comment]
This  branch will be merged instead of rebased. PR of merge can be found at #2611.

**Pull request closed without merging**
