### PR TITLE
Type the interfaces

### PR DESCRIPTION
**Pull request by TavoNiievez**

### CODE REVIEW

**Review by Naktibalda — APPROVED** [review]
Looks good to me

**Comment by DavertMik** [comment]
This is a good initiative but I'd rather not update interfaces for modules. 
This will break compatibility with all our current modules and 3rd-party modules as well. 

It is a really good idea to update the internal interfaces of Codeception to new standards. But all interfaces that are reused to other modules must be kept the same.

**Comment by TavoNiievez** [comment]
Hi @DavertMik 
 
> "This will break compatibility with all of our current modules."

It's true, but I also promised to update the vast majority of modules (both the most downloaded and those that have received at least one commit in the last year). So this will not really affect anyone who requires the new versions of the modules and Codeception 5 because they will be compatible from day one.

> "and 3rd-party modules as well."

The amount of time required to update the implementation of these interfaces is minimal since the interface itself will guide the change.

> "all interfaces that are reused to other modules must be kept the same."

Forever and ever?
Please keep in mind that a major version is a great opportunity to do this.

Also remember that this directly affects the implementation of the Fluent interface in Codeception 5 that you agreed with.

Please take some time to reconsider.

**Review by DavertMik — APPROVED** [review]

**Comment by DavertMik** [comment]
Thanks, @TavoNiievez I agree on all points.
If all modules will be updated I'm ok with this.

**Pull request merged**
