### PR TITLE
Fix bug with void type not being picked up correctly

### LINKED ISSUE #5877: A void function must not return a value error since 4.1.2
Caused by #5862 

#### What are you trying to achieve?

Return types on generated actions for methods that return `void` should not use `return` since you cannot return a `void`:

```php
public function voidMethod(): void {
    $this->getScenario()->runStep(new \Codeception\Step\Action('voidMethod', func_get_args()));
}
```

#### What do you get instead?

```php
public function voidMethod(): void {
    return $this->getScenario()->runStep(new \Codeception\Step\Action('voidMethod', func_get_args()));
}
```

This causes PHP errors:

```
Fatal error:  A void function must not return a value
```
### Details

* Codeception version: 4.1.2
* PHP Version: 7.3.15
* Operating System: Ubuntu 18.04.3
* Installation type: Composer

### PR DESCRIPTION
**Pull request by Jamesking56**
Fixes #5877 

My previous PR (#5878) had a slight problem in that I assumed that `$returnType` just had the return type on its own in it (e.g. `void`). However it does not, it also includes the `: ` before it.

### CODE REVIEW

**Comment by Jamesking56** [comment]
Tested this with my project (editing vendor directly) and it works!

**Comment by Jamesking56** [comment]
@Naktibalda tests added and passing

**Comment by Naktibalda** [comment]
Thank you

**Comment by Naktibalda** [comment]
Released as 4.1.4

**Pull request merged**
