### PR TITLE
Fixtures behavior compability with `yii2-codeception`

### PR DESCRIPTION
**Pull request by leandrogehlen**
The same behavior on load fixtures:
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L85

### CODE REVIEW

**Comment by boboldehampsink** [comment]
yii2-codeception is deprecated

**Comment by leandrogehlen** [comment]
@boboldehampsink Yes, the features was moved to yii2 module in codeception, and this implementation was not, then the behavior is different, and this change it's necessary.

**Comment by boboldehampsink** [comment]
Ah yeah, my bad 👍

**Comment by samdark** [comment]
@DavertMik looks OK to merge.

**Pull request merged**
