### PR TITLE
Allow sebastian/diff 2.* in composer.json

### LINKED ISSUE #4505: Laravel 5.5 not supported
#### What are you trying to achieve?
install codeception for laravel 5.5
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
hendros-MacBook-Air:codeceptest hendroutomo$ docker run --rm -v $(pwd):/app composer/composer require codeception/codeception
Using version ^2.3 for codeception/codeception
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeception/codeception 2.3.0 requires phpunit/phpunit >4.8.20 <6.0 -> satisfiable by phpunit/phpunit[4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26, 4.8.27, 4.8.28, 4.8.29, 4.8.30, 4.8.31, 4.8.32, 4.8.33, 4.8.34, 4.8.35, 4.8.36, 4.8.x-dev, 5.0.0, 5.0.1, 5.0.10, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.0.x-dev, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.10, 5.2.11, 5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.2.x-dev, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7, 5.4.8, 5.4.x-dev, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 5.5.7, 5.5.x-dev, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.x-dev, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install codeception/codeception 2.3.5
    - Conclusion: don't install codeception/codeception 2.3.4
    - Conclusion: don't install codeception/codeception 2.3.3
    - Conclusion: don't install codeception/codeception 2.3.2
    - Conclusion: remove sebastian/diff 2.0.1
    - Installation request for codeception/codeception ^2.3 -> satisfiable by codeception/codeception[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5].
    - Conclusion: don't install sebastian/diff 2.0.1
    - codeception/codeception 2.3.1 requires sebastian/diff ^1.4 -> satisfiable by sebastian/diff[1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Can only install one of: sebastian/diff[1.4.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.3, 2.0.1].
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].


Installation failed, reverting ./composer.json to its original content.
```
### Details

* Codeception version: 2.3
* PHP Version: 7
* Operating System: MacOSX Sierra running Docker
* Installation type: Composer

### PR DESCRIPTION
**Pull request by Naktibalda**
Fixes #4505

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks!

**Comment by Naktibalda** [comment]
The build failed, so merging this PR wasn't a good idea.

**Comment by Naktibalda** [comment]
```
There was 1 failure:

---------

1) DiffFactoryTest: It creates message for comparison failure

 Test  tests/unit/Codeception/Lib/Console/DiffFactoryTest.php:testItCreatesMessageForComparisonFailure
The diff should be generated.
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-     <body>Don't forget me this weekend!</body>\n
- </note>\n
#1  /home/travis/build/Codeception/Codeception/tests/unit/Codeception/Lib/Console/DiffFactoryTest.php:27
#2  Codeception\Lib\Console\DiffFactoryTest->testItCreatesMessageForComparisonFailure
#3  /home/travis/build/Codeception/Codeception/codecept:36
```

**Comment by Naktibalda** [comment]
I have no time to test it now, but I can try to find some time tonight or some other evening this week.

**Pull request merged**
