### PR TITLE
Optional Di service in Unit tests

### PR DESCRIPTION
**Pull request by Bakhtarian**
The `Di` should not be required when running a unit test. This caused issues in my setup when I tried to use `@dataProvider` in the Unit test.

## Expected response:

````shell
Unit Tests (6) --------------------------------------------------------------------------------------------------------------------------------------------------------
✔ RequestHeaderTest: It should run test with data provider | #0 (0.01s)
✔ RequestHeaderTest: It should run test with data provider | #1 (0.00s)
✔ RequestHeaderTest: It should run test with data provider | #2 (0.00s)
✔ RequestHeaderTest: It should run test with data provider | #3 (0.00s)
✔ RequestHeaderTest: It should run test with data provider | #4 (0.00s)
✔ RequestHeaderTest: It should run test with data provider | #5 (0.00s)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
````

## Actual response:
````shell
[PHPUnit\Framework\Error] The data provider specified for DataProviderTest::testItShouldRunTestWithDataProvider is invalid.
Codeception\Exception\InjectionException: Service di is not defined and can't be accessed from a test
//tests/unit/DataProviderTest:157
//tests/unit/DataProviderTest:87
````

### CODE REVIEW

**Comment by Naktibalda** [comment]
How did you make `di` service disappear?

**Comment by Bakhtarian** [comment]
I only installed the `unit` testing suite.

Steps;

````shell
composer require "codeception/codeception" --dev
php vendor/bin/codecept init unit
````
This created the following directories and files:

````shell
| tests
|____ _output
|____ _support
|____ unit
|____ unit.suite.yml
````

My `unit.suite.yml` :
````yaml
actor: UnitTester
modules:
  enabled:
    - Asserts
  step_decorators: ~
````

**Comment by Naktibalda** [comment]
Could you provide the code of DataProviderTest.php file?
Remove all unnecessarry details.

**Comment by Bakhtarian** [comment]
Don't have that file, these are the only ones I have:

filename_08_13_

**Comment by Naktibalda** [comment]
How come you had `//tests/unit/DataProviderTest` in your `Actual Response` section?

Did you fake that response? :)

**Comment by Naktibalda** [comment]
`@dataProvider` annotation works in test classes extending `\Codeception\Test\Unit` and `\PHPUnit\Framework\TestCase` classes.

**Comment by Naktibalda** [comment]
This change is not necessary.

**Pull request closed without merging**
