### PR TITLE
Does Codeception support PHP 7.3?

### PR DESCRIPTION
**Pull request by svycka**

### CODE REVIEW

**Comment by svycka** [comment]
hmm I am a bit lost why tests pass on travis but localy I get:
```
Fatal error: Declaration of Codeception\Test\Test::run(?PHPUnit\Framework\TestResult $result = NULL) must be compatible with PHPUnit\Framework\Test::run(?PHPUnit\Framework\TestResult $result = NULL): PHPUnit\Framework\TestResult in /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Test.php on line 18
```

**Comment by Naktibalda** [comment]
Yes, Codeception supports PHP 7.3, but as you can see some framework testsuites don't.
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorExcepti  
  on: Warning: "continue" targeting switch is equivalent to "break". Did you   
  mean to use "continue 2"? in /home/travis/build/Codeception/Codeception/fra  
  mework-tests/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 26  
  36 
```
This error should be easy to fix in `doctrine/orm` library.

Three Yii2 tests fail because they call `assertContains` method of `codeception/verify` library which calls deprecated PHPUnit method `assertContains` in turn.
This issue must be fixed in `codeception/verify`: https://github.com/Codeception/Verify/issues/38

Alternatively, we can disable Symfony and Yii2 tests on PHP 7.3


```
 Test  ../../vendor/yiisoft/yii2-app-advanced/frontend/tests/unit/models/ContactFormTest.php:testSendEmail
                                                                                                                                                                                                                                              
  [PHPUnit\Framework\Warning] Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.  
                                                                                                                                                                                                                                              
#1  /home/travis/build/Codeception/Codeception/codecept:43
2) ResendVerificationEmailFormTest: Successfully resend
 Test  ../../vendor/yiisoft/yii2-app-advanced/frontend/tests/unit/models/ResendVerificationEmailFormTest.php:testSuccessfullyResend
                                                                                                                                                                                                                                              
  [PHPUnit\Framework\Warning] Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.  
                                                                                                                                                                                                                                              
#1  /home/travis/build/Codeception/Codeception/codecept:43
3) SignupFormTest: Correct signup
 Test  ../../vendor/yiisoft/yii2-app-advanced/frontend/tests/unit/models/SignupFormTest.php:testCorrectSignup
                                                                                                                                                                                                                                              
  [PHPUnit\Framework\Warning] Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.  
                                                                                                                                                                                                                                              
#1  /home/travis/build/Codeception/Codeception/codecept:43
```

**Comment by DavertMik** [comment]
Yeah, disabling failing framework tests is fine. Thanks @svycka we really need to get php 7.3 into the test suite

**Comment by SamMousa** [comment]
Please create issues for yii and assign them to me!

**Comment by Naktibalda** [comment]
@SamMousa it isn't an issue of Yii app, `assertContains` is called by `codeception\verify`: https://github.com/Codeception/Verify/issues/38

**Pull request closed without merging**
