### PR TITLE
Clear header and cookie collections before request

### PR DESCRIPTION
**Pull request by SamMousa**
https://github.com/Codeception/Codeception/issues/4587

### CODE REVIEW

**Comment by SamMousa** [comment]
@samdark ping :)

**Comment by samdark** [comment]
Looks OK to me but there are Travis failures. Any idea if these are connected (I'm not sure)?

**Comment by DavertMik** [comment]
Yes, it is related. See https://travis-ci.org/Codeception/Codeception/jobs/306390142#L3610

And I don't think this is a good patch. @samdark If you think this should be implemented, the Yii client shoud use public API of Yii framework, and not access private variables. I think Yii can provide such API

**Comment by SamMousa** [comment]
@DavertMik I agree that it is not desirable, in my bug report I mentioned it was an ugly fix approach. At the moment it is the only one that does not require a change in the public API of the framework.
If it is part of the public API of the framework then it must be maintained.
As it currently stands the implementation of the testing module is already tightly coupled to the framework.

Anyway, that's something that you guys have to decide and in this case I won't be offended if you choose to close this PR based on your argument.

Side note: fixed my PR, this is why one should not use the GitHub editor to make PRs :-(

**Comment by samdark** [comment]
@SamMousa indeed. It's not fixed :)

**Comment by erickskrauch** [comment]
@DavertMik https://github.com/Codeception/Codeception/pull/4651 I have another suggestion about this issue.

**Pull request closed without merging**
