### PR TITLE
fix Step::addMetaStep by dereferencing stack arguments that may have …

### PR DESCRIPTION
**Pull request by alambe**
…been passed-by-reference, so that later modules like console do not clobber original referenced value by accident

Quick fix for issue #4402

### CODE REVIEW

**Comment by alambe** [comment]
Is this being considered or are you waiting on me to do something?  I'm not sure why semaphore failed.  It passed before and the only changes since were nitpick formatting fixes.  I did push two nitpick fix commits in rapid succession (the second before the first's checks completed), and this could have caused an issue for semaphore.  Should I push an empty commit to trigger checks to run again?  Or, can someone with access re-run the semaphore check or direct me how to do that?

**Comment by alambe** [comment]
Thank you.

**Comment by DavertMik** [comment]
Just a guess, can this be solved with `array_map`? I would prefer it in this case

**Comment by alambe** [comment]
Are you suggesting to just replace `array_values($step['args'])` with `array_map(null,$step['args']);`?

`array_map` without a callback does not dereference values.  Also, it maintains keys while `array_values` rekeys.  With my change, I was trying to maintain the rekeying behavior of array_values, though I don't know if rekeying is necessary.  If rekeying was not necessary, why was array_values used in the first place?

That said, if rekey is not necessary, then yes, the following should work:
`array_map(function($i){return $i;},$step['args'])`

If rekeying is necessary, the following will dereference and rekey:
`array_map(function($i){return $i;},array_values($step['args']))`

The later is functionally equivalent to the existing patch.  Do you want me to update the branch?

**Comment by DavertMik** [comment]
Sorry for late response... @alambe but yes, I prefer this:

```php
array_map(function($i){return $i;},array_values($step['args']))
```

please!

**Comment by alambe** [comment]
No problem.  I'm just glad to get this fix in upstream.

**Comment by DavertMik** [comment]
Thanks very much! Sorry for the delay in responses and this strictness about the code )

**Pull request merged**
