### PR TITLE
[Doctrine2] Make haveInRepository support constructor parameters

### PR DESCRIPTION
**Pull request by burned42**
Closes https://github.com/Codeception/Codeception/issues/5632 (please also note the comments there).

### CODE REVIEW

**Comment by burned42** [comment]
@alexkunin That's a good idea, I'm throwing an exception now in this case: b246c801ce6e4fd9b416ffe097cc647d0babb026

**Comment by alexkunin** [comment]
Do you think adding a test or two is possible? There is a suite for `Doctrine2`, adding an entity with constructor parameters and a test case for that should not be hard. Let me know if you need help with that.

**Comment by burned42** [comment]
@alexkunin Actually I already added some [tests](https://github.com/Codeception/Codeception/pull/5633/files#diff-22979855156ba9918a2157667379ffbb). Did you just miss them, or do you think I should add more tests?

**Comment by alexkunin** [comment]
Yep, missed them, was writing my comment when https://github.com/Codeception/Codeception/pull/5633/commits/b246c801ce6e4fd9b416ffe097cc647d0babb026 was not there yet (or at least was not displayed by UI). They look good to me, nothing to add. Maybe mention in method docblock that fields that match constructor parameters are passed to constructor instead of direct property assignment, along with 1-2 lines of sample code? And after that I'd summon @Naktibalda or @DavertMik for their review.

**Comment by burned42** [comment]
@alexkunin sure, adding a comment would be nice, let me just make sure I get this correctly. Where would be the best place to add this comment? On first thought I would add it to the method `setPropertiesForClass` that I actually changed, but on the other side, the docblock of `Doctrine2::haveInRepository` is what the end users see (this is what you see in the documentation, right?), so would that maybe be a better place to add such a comment?

**Comment by alexkunin** [comment]
`Doctrine2::haveInRepository` is the only valid place to add the comment if you want it to make it to the docs. I mean, comments on that utility class are not exactly useless, but not a part of user docs. If you want to preview your doc changes, see https://github.com/Codeception/Codeception/blob/3.0/RELEASE.md for general info on building, and then use `php robo.phar build:docs` (IIRC) to build only docs (they go to `docs/` directory).

**Comment by burned42** [comment]
@alexkunin I tried to explain the behavior in f9dd006138c6d3fc229abe21e369724a4e1b3143

I'm not quite sure how a code example could look like as it could just be the same as the examples that already exist, given the mentioned `Entity\User` would have a constructor. If you have any suggestions, I'd be happy to add those :)

**Comment by alexkunin** [comment]
The following would make sense to me:

> ```php
> $I->haveInRepository(new User($arg), array('name' => 'davert'));
> ```
> 
> Alternatively, constructor arguments can be passed by name. Given `User` constructor signature is `__constructor($arg)`, example above could be rewritten like this:
> 
> ```php
> $I->haveInRepository('User', array('arg' => $arg, 'name' => 'davert'));
> ```

**Comment by alexkunin** [comment]
Looks good to me. I'd say maintainers (given they are willing to merge this PR) will ask to squish commits, but maybe wait until they say so. Other than that, I can't see anything to add here except our edge cases. But this is probably should be discussed in the issue first.

**Comment by burned42** [comment]
@alexkunin Thank you very much :)

**Comment by alexkunin** [comment]
You're welcome! BTW, all tests are green, which means this PR is ready for real review from maintainers.

**Comment by Naktibalda** [comment]
@alexkunin Please resolve merge conflict in the docblock.

**Comment by burned42** [comment]
@Naktibalda since I opened the PR I tried to resolve the merge conflicts myself. Apparently it was a bit more than just the docblock because @alexkunin recently introduced the nested entity creation which broke my implementation :D Anyway, I rebased onto 3.0, resolved the merge conflicts and adapted my code to work with the latest changes (see last two commits). CI seems to be happy with it :)

**Comment by Basster** [comment]
This PR broke `haveInRepository`, so you cannot pass a pre populated object wich has constructor arguments.

```php
class A(B $b) {}

classs B() {}

$b = new B();
$a = new A($b);

$I->haveInRepository($a)
```
Results in `[InvalidArgumentException] Constructor parameter "b" missing`.

I'm going to try submiting a fix today, as I'm already figuring out, how to fix this.

**Comment by burned42** [comment]
@Basster you are totally correct :man_facepalming: I must've missed that when I resolved the merge conflicts (when I started this PR, `haveInRepository` didn't even have the possibility to work with pre-populated objects). Constructor parameters currently get checked always, even if a pre-populated object gets passed and if one is missing the exception gets thrown, but of course if we already have a pre-populated object then we don't need to have those constructor parameters at all.

Did you already find out how to fix this? Otherwise I can also open a PR to fix this.

**Comment by Basster** [comment]
Will submit the PR in a few seconds ^^

**Pull request merged**
