### PR TITLE
Use `andWhere` instead of `where`

### PR DESCRIPTION
**Pull request by SamMousa**
See https://github.com/yiisoft/yii2/issues/14757

### CODE REVIEW

**Comment by samdark** [comment]
I confirm the change is correct.

**Comment by SamMousa** [comment]
It seems tests are broken by another cause.

**Comment by Naktibalda** [comment]
The cause was that you made a PR to master branch, bugfixes and backwards compatible features should be merge to the current active branch (2.3).

**Comment by SamMousa** [comment]
My bad.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
