### PR TITLE
Group file with example tests

### PR DESCRIPTION
**Pull request by eXorus**
Test PR #3311

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks but currently it fails on Appveyor. What can be Windows-specific here?

**Comment by DavertMik** [comment]
I think this can be merged after 2.2.5 release. However we need to have Windows test fixed:

```
There was 1 failure:
---------
1) RunCest: Run test with annotation examples from group file
 Test  tests\cli\RunCest.php:runTestWithAnnotationExamplesFromGroupFile
 Step  See in shell output "OK (10 tests"
 Fail  Failed asserting that 'Codeception PHP Testing Framework v2.2.4
Powered by PHPUnit 5.5.5 by Sebastian Bergmann and contributors.
[Groups] groupFile1
Scenario Tests (0) -----------------------------------------
------------------------------------------------------------
Time: 664 ms, Memory: 8.00MB
No tests executed!' contains "OK (10 tests".
Scenario Steps:
 3. $I->seeInShellOutput("OK (10 tests")
 2. $I->executeCommand("run scenario -g 
```

**Comment by eXorus** [comment]
There is nothing Windows-specific just the path maybe windows doesn't like. For this test I need that sandbox have the file tests/_data/groupFile1 ...

Why there is so much: The process cannot access the file because it is being used by another process

**Comment by eXorus** [comment]
@DavertMik @Naktibalda Any help about this Windows behaviour I don't have windows so I can't understand the error ?

Is "Claypit + Sandbox" working on Windows ?

**Comment by eXorus** [comment]
After some tests I can't understand the issue on Windows.
The file tests/data/claypit/tests/_data/groupFile1 is present.

**Test 1**
run tests/scenario/ExamplesCest.php => OK

**Test 2**
run -g groupFile1 => KO
codeception.yml
```
...
groupFile1: [tests/scenario/ExamplesCest.php]
...
```

**Test 3**
run -g groupFile1=> KO
codeception.yml
```
...
groupFile1: tests/_data/groupFile1
...
```

 tests/_data/groupFile1
```
...
tests/scenario/ExamplesCest.php
...
```

I don't see tests about group files with Windows is it working ?

**Pull request closed without merging**
