### PR TITLE
Fix encoding problems in PHP prior to 5.6 related to #2831

### PR DESCRIPTION
**Pull request by pejaycz**
Fix encoding problems, #2831 redone for master branch

### CODE REVIEW

**Comment by raistlin** [comment]
Seems good to me.
@Naktibalda, are all your modifier mb_* changed here?

**Comment by samdark** [comment]
Yes, looks good.

**Comment by samdark** [comment]
Thank you!

**Comment by samdark** [comment]
@DavertMik should it be merged to any other branch?

**Pull request merged**
