### PR TITLE
Fix "@depends doesnt work with @dataprovider" #3862

### PR DESCRIPTION
**Pull request by edno**
Fix for the issue "**@depends doesnt work with @dataprovider**" #3862

### CODE REVIEW

**Comment by edno** [comment]
@DavertMik before merging this PR (if you think it can be merged), I suggest to wait for @Fuin's feedback on #3862

**Comment by DavertMik** [comment]
Thanks! Let's wait for it

**Comment by edno** [comment]
Positive feedback from @Fuin, so the PR is ready to go 🚀

**Comment by DavertMik** [comment]
Ok, well done. Thank you!

**Pull request merged**
