### PR TITLE
Update Symfony1.php

### PR DESCRIPTION
**Pull request by LeeKevin**
Fix for https://github.com/Codeception/Codeception/issues/789. Broken call to Framework::formatResponse.

### CODE REVIEW

**Comment by LeeKevin** [comment]
Fix for Codeception#789. Broken call to Framework::formatResponse.

**Comment by DavertMik** [comment]
Wow, you are brave to use symfony1 and codeception 1.8 these days )
Probably you can't do upgrade for symfony but I'd recommend you to upgrade Codeception to 2.1 and send this PR into https://github.com/Codeception/symfony1module (we moved symfony module there)

**Comment by DavertMik** [comment]
And thank you!

**Comment by LeeKevin** [comment]
Haha I'm not using symfony1 by choice!

**Pull request merged**
