### PR TITLE
Added Codeception\Module\Db::seeNumRecord

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@DavertMik

**Comment by enumag** [comment]
@sergeyklay You should squash the commits.

**Comment by DavertMik** [comment]
@sergeyklay yeah, I learned to do this recently. Please try it too https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by DavertMik** [comment]
ok, nevermind, I want to get 2.1 released today

**Pull request merged**
