### PR TITLE
Configurable output limit for data provider

### PR DESCRIPTION
**Pull request by mlambley**
Closes https://github.com/Codeception/Codeception/issues/4994

Should not break anything - it will use the current default value if the new settings are not specified.

Any feedback will be appreciated. Thank you.

### CODE REVIEW

**Comment by DavertMik** [comment]
Sorry I have some concerns about it.

1. You add a new config value which most of the users won't be aware of...
2. You change the signature to core classes.

Maybe there should be some sane defaults instead of configuration option which no one would reconfigure?

**Comment by mlambley** [comment]
Putty's line length is around 200 but cmd.exe is around 100. I don't think that there can be a sane default.

**Comment by DavertMik** [comment]
Can this be done via environment variable then?

**Comment by mlambley** [comment]
I'm not certain how your environment variables work, but looking at:

https://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters
https://codeception.com/docs/07-AdvancedUsage#Environments

I see that they allow you to group different configurations and specify which to use, either in the CLI or in the code. However, in both instances they need to be configuration options in the first place.

Could you give me more information regarding your suggestion that the line length be changed via an environment variable? Thanks.

**Comment by edno** [comment]
Maybe configuration as part of the [parameters for `run` command line](https://codeception.com/docs/reference/Commands#Run) .
Something like: `--output-limit=200`

**Comment by Naktibalda** [comment]
This PR died from the old age.

**Pull request closed without merging**
