### PR TITLE
Don’t skip empty strings in headers.

### LINKED ISSUE #4287: Empty values for headers are skipped
#### What are you trying to achieve?
I'm trying to set a `DNT` header to the value of `0`, as it is described in the specification:

    $I->haveHttpHeader('DNT', '0');

#### What do you get instead?
The `DNT` header is not set to the server as it is skipped.

### Details
The problem is in this line of code: https://github.com/Codeception/Codeception/blob/b54eaf4007484f36145c1dc8c64da1874adbc340/src/Codeception/Lib/InnerBrowser.php#L156-L158.

The string value `0` is evaluated as false and will not be send.
A possible solution would be to check if the value is a string, and if it is use it anyway. I could create a pull request for this, if it is an acceptable fix for you.

### PR DESCRIPTION
**Pull request by tobiastom**
This will close #4287.

### CODE REVIEW

**Comment by Naktibalda** [comment]
I find it ironic that it still skips empty string ''.

**Comment by tobiastom** [comment]
That's the intended behaviour, right?

For me I din't see why this check is there in the first place. Either I set a header, or I delete it. When I delete it, `deleteHeader` will unset it.

**Comment by DavertMik** [comment]
Thanks!

**Comment by tobiastom** [comment]
Thanks you the merge! :-)

**Pull request merged**
