### PR TITLE
Wrong format in BrowserStack host address

### PR DESCRIPTION
**Pull request by javigomez**

### CODE REVIEW

**Comment by DavertMik** [comment]
Oups. I will update docs myself as it should be done in WebDriver module itself

**Comment by javigomez** [comment]
Oh! Ok, so if I see an issue next time, I have only to modify the docblock at the module: src/Codeception/Module/`module`.php... right? and then do I need to run some Robo command to generate docs? 

I saw https://github.com/Codeception/Codeception/commit/b38b519220ed5f877c081c7de8331ecb1dd607fa but not sure to understand the process.

**Comment by DavertMik** [comment]
> and then do I need to run some Robo command to generate docs?

Yes, it's `robo build:docs`

**Comment by javigomez** [comment]
nice! thanks :+1:

**Pull request closed without merging**
