### PR TITLE
Add Laravel 5 module files

### PR DESCRIPTION
**Pull request by janhenkgerritsen**
Laravel 5 now has a stable release, so the Laravel 5 module I created and maintained during the Laravel 5 development period can now be added to Codeception. The files in this pull request are the files from https://github.com/janhenkgerritsen/codeception-laravel5.

A sample app similar to the sample app of the Laravel 4 module can be found at https://github.com/janhenkgerritsen/codeception-laravel5-sample. This sample app uses the code in the repository mentioned above. From the sample app I removed the cli test suite, since the tests in that suite only used the Cli module and no functionality specific to the Laravel module was used.

I also added my own personal details as information about the maintainer of the module, is that ok?

### CODE REVIEW

**Comment by DavertMik** [comment]
:+1:

**Comment by DavertMik** [comment]
That's great! I will add your sample app to `.travis.yml` of Codeception. Please keep it stable and do not delete it =) Laravel5 will have updates, so this sample app should either be fixed to specific Laravel version or being updated with each release (which is preferable).

> I also added my own personal details as information about the maintainer of the module, is that ok?

That's awesome. Finally there is a maintainer for Laravel module )

**Comment by DavertMik** [comment]
Nice. Tests are passing:

https://travis-ci.org/Codeception/Codeception/jobs/50142846#L9430

**Comment by janhenkgerritsen** [comment]
Great! I will not delete the sample app and keep it up to date with the latest releases of Laravel 5.

**Pull request merged**
