### PR TITLE
Support utf-8 by gherkin snippets generator

### LINKED ISSUE #4100: Empty function name when generating snippets for non-english gherkin scenarios
#### What are you trying to achieve?

Given gherkin scenario `Utf8Example.feature` written in russian 
```gherkin
#language: ru

Функционал: Генерация сниппетов из сценариев на других языках
    ...
    Сценарий: Генерация сниппета из сценария на русском языке
        Допустим я написал сценарий на русском языке
```
When I run `codecept gherkin:snippets cli Utf8Example.feature`
Then I want to see generated snippet
```php
    /**
     * @Given я написал сценарий на русском языке
     */
     public function ЯНаписалСценарийНаРусскомЯзыке()
     {
        throw new \Codeception\Exception\Incomplete("Step `я написал сценарий на русском языке` is not defined");
     }
```
#### What do you get instead?

Snippet is generated but function name is not specified (blank):

```php
    /**
     * @Given я написал сценарий на русском языке
     */
     public function ()
     {
        throw new \Codeception\Exception\Incomplete("Step `я написал сценарий на русском языке` is not defined");
     }
```
### Details

* Codeception version: 2.2.9

### PR DESCRIPTION
**Pull request by kuntashov**
Fixes #4100

### CODE REVIEW

**Comment by Naktibalda** [comment]
AppVeyor build has failed:

https://ci.appveyor.com/project/DavertMik/codeception/build/1.0.3765#L395
```php
     public function �НаписалСценарийНаРусскомЯзыке()
     {
        throw new \Codeception\Exception\Incomplete("Step `я написал сценарий на русском языке` is not defined");
     }
```

**Comment by kuntashov** [comment]
@Naktibalda Thanks for pointing out.
I have seen that, but need some time to figure out why this happens.

I tried to create my own AppVeyor project to reproduce and debug this error but it failed with messages:

```bash
Failures
 - kb2999226 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2999226\tools\chocolateyinstall.ps1'.
 See log for details.
 - kb2919442 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2919442\tools\ChocolateyInstall.ps1'.
 See log for details.
 - kb3035131 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.
Command exited with code 1058
```

Is there some specific settings for AppVeyor to build Codeception?

**Comment by Naktibalda** [comment]
Have you tried to run your tests on Windows?

**Comment by kuntashov** [comment]
@Naktibalda No, I have no Windows installed and thought it whould be easyest way to create my own AppVeyor project.

I'm going to install Windows VM.

**Comment by kuntashov** [comment]
@Naktibalda Bug that caused AppVeyor build to fail was fixed.

**Comment by DavertMik** [comment]
```
public function яНаписалСценарийНаРусскомЯзыке
```

why would you ever need this? 
You can't write PHP code using Russian charset. Yes, there is a problem in snippet generation but I don't think that Codeception should generate such weird method names.  

Step should match the annotation but you can use a different name for the method.

```php
/**
 * @Given я написал сценарий на русском языке
 */
public function wroteScenarioInRussian()
```

I'd propose to simplify this generator. If name is empty, then method name can be generated like `public function step0001()`.

**Comment by kuntashov** [comment]
@DavertMik 

> why would you ever need this?

E.g. for code navigation in text editor/IDE.

> You can't write PHP code using Russian charset.

Technically I can use any utf8 symbols in as variable or method name in PHP since 5.6 actually.

>  method name can be generated like public function step0001()

This method name is useless and mess up IDE's method list.

**Comment by DavertMik** [comment]
> Technically I can use any utf8 symbols in variable or method name in PHP since 5.6 actually.

Technically it is useless, as `$` char is not available in Russian charset. So you will still need to switch to English layout. You won't be able to interact with that method without constantly switching keyboard layout. Probably this can lead to potential charset problems, which we can't predict. So I'd not take a risk and introduce such methods even as stubs. I don't want to start receiving issues like: "why my code `$this->为知笔记全端春节前的()` is not working? It was generated by Codeception!"

> This method name is useless and mess up IDE's method list.

But this is a stub, so you can change it to a proper name.

**Comment by kuntashov** [comment]
@DavertMik Ok

**Pull request closed without merging**
