### PR TITLE
PHPUnit 7 support

### PR DESCRIPTION
**Pull request by DavertMik**
* PHPUnit 7 
* Phar build improvements

### CODE REVIEW

**Comment by riotCode** [comment]
@DavertMik on appveyor/pr the error is abrupt, no context for it unless it's the "Json type matches" test but that looks like it's successful. Only thing I could find related to this error: https://help.appveyor.com/discussions/problems/4873-command-exited-with-code-1073741819

**Comment by DavertMik** [comment]
Yeah, that was temporary Appveyor issue. Let me merge it before it started failing again 😊

**Comment by dhensby** [comment]
I've tried to get this working locally but composer is unable to resolve the dependencies because `phpunit/phpunit:^7` requires `sebastian/diff:^3` but this library requires `sebastian/diff:>=1.4 <3.0`

It looks like the `sebastian/diff` dependency needs a bump too...

**Comment by dhensby** [comment]
Ah, seems like this is a known issue: https://github.com/Codeception/Codeception/pull/4816

**Pull request merged**
