### PR TITLE
Naive phar self update command for 4.0

### PR DESCRIPTION
**Pull request by Naktibalda**
It unconditionally fetches latest codecept.phar from website.
Smarter implementation requires storing phar version (X.Y.Z.DATE) in the phar file
and the latest phar version somewhere on the website.

Please do `Squash and Merge` if I forget to squash commits myself.

### CODE REVIEW

**Comment by Naktibalda** [comment]
It works like this:
```
$ php codecept.phar self-update
Codeception version 4.0.0

Updating...

codecept.phar has been updated.

$ php codecept.phar
Codeception 3.1.2
```

**Comment by Naktibalda** [comment]
`self-update` on older versions of PHP fails, because there is no php56/codecept.phar file until https://github.com/Codeception/codeception.github.com/pull/189 is merged
```
$ php5.6 codecept.phar self-update
Codeception version 4.0.0

Updating...

Request failed.
```

**Comment by SamMousa** [comment]
We could look at something like this:

https://github.com/humbug/phar-updater

**Comment by Naktibalda** [comment]
Basic SHA-1 strategy looks like a good idea, but it is a shame that phar/updater was abandoned.
It is ironic that to projects given as examples in https://github.com/humbug/phar-updater/issues/53 removed selfupdate commands completely.

**Comment by SamMousa** [comment]
What those project recommend is using https://phar.io/
I looked at that when it was still in its infancy and it didn't go very well plugins.

**Comment by Naktibalda** [comment]
I implemented new SelfUpdate command using phar-updater at  #5747
Related change in build script at https://github.com/Codeception/codeception.github.com/pull/189/commits/b0ca9ec87bd446aa9556fc7f395ae0b0b21c17e4

Now I need to figure out why https://github.com/Codeception/codeception.github.com/blob/master/codecept.version doesn't work as https://codeception.com/codecept.version

**Pull request closed without merging**
