### PR TITLE
new REST / InnerBrowser Asserts

### PR DESCRIPTION
**Pull request by johannesschobel**
This PR adds new assertions to check, if a `HttpStatusCode` is between a certain range (e.g., `4xx`) and provides "wrappers" for common blocks..

For example:
- `seeStatusCodeIsSuccessful()` checks for `2xx`
- `seeStatusCodeIsClientError()` checks for `4xx`
and so on..

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks. Sorry for CI, it is failing for external project so it should not bother you right now.
But can you implement a test for those methods? That should be useful

**Comment by johannesschobel** [comment]
Dear @DavertMik ,

i would love to add a test, however, I was not sure where / how to implement it. I found a `RestTest` (or something like this) class that contains tests for the `REST` module. However, I could not get it to work locally on my dev machine. Further, the endpoints most likely only return `200` or `404` ;)

Do you have an idea how to properly test it? I found a page that returns specific http status codes ( https://httpstat.us/ ) . Maybe i can use this to "fake" some codes and properly test them!? What do you think?

**Comment by johannesschobel** [comment]
ok, sorry.. actually i was quite dumb.. added some tests for the methods as requested..

**Comment by DavertMik** [comment]
Awesome! Thank you!

**Comment by johannesschobel** [comment]
Hey @DavertMik , thanks a lot for merging..
Just a quick question: Are you interested in additional `assert` functions for specific modules? In this case i could / would love to add additional features.. Just drop me a line if you are interested..

All the best,
Johannes

**Pull request merged**
