### PR TITLE
Filter HTML report.

### PR DESCRIPTION
**Pull request by raistlin**
Implement issue #1669 
Added a 'toolbar' for easy filtering.

Click on every statusCode toogle visibility of given status, additionally there is a "Show all" button.

### CODE REVIEW

**Comment by raistlin** [comment]
Broken tests are unrelated to my changes.

**Comment by DavertMik** [comment]
@rafreis yeah, to fix tests you can merge with latest 2.0 changes. 
Anyway, I see all the core tests did pass, so no problems with it. Let me review the commit.

**Comment by DavertMik** [comment]
Looks useful! Let me try it in action :+1:

**Comment by DavertMik** [comment]
@rafreis Oh.. Could you send this PR to 2.0 branch as well? 
master is used for major changes so your PR will be available only since 2.1

**Comment by raistlin** [comment]
Sent



—
Enviado desde Mailbox

**Pull request merged**
