### PR TITLE
[InnerBrowser] Debug redirects

### PR DESCRIPTION
**Pull request by Naktibalda**
Before
```
Running PhpBrowserTest::testHeadersRedirect...
  [Response] 200
  [Page] http://localhost:8000/info
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"]}
PhpBrowserTest::testHeadersRedirect                                                         Ok
```

After
```
Running PhpBrowserTest::testHeadersRedirect...
  [Response] 302
  [Page] http://localhost:8000/redirect
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"],"Location":["/info"]}
  [Redirecting to] /info
  [Response] 200
  [Page] http://localhost:8000/info
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"]}
PhpBrowserTest::testHeadersRedirect                                                         Ok
```

### CODE REVIEW

**Comment by Naktibalda** [comment]
I will implement support for multiple redirects.

**Comment by Naktibalda** [comment]
I think that printing Page before Response code is more logical.
```
Running PhpBrowserTest::testChainedRedirects... 
  [Page] http://localhost:8000/redirect_twice
  [Response] 302
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"],"Location":["/redirect3"]}
  [Redirecting to] /redirect3
  [Page] http://localhost:8000/redirect3
  [Response] 302
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"],"Refresh":["0;url=/info"],"Location":{}}
  [Redirecting to] /info
  [Page] http://localhost:8000/info
  [Response] 200
  [Cookies] []
  [Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"]}
PhpBrowserTest::testChainedRedirects                                                        Ok
```

**Comment by Naktibalda** [comment]
I will take into account that followRedirects can be disabled by the test code: https://github.com/Codeception/Codeception/pull/2336

**Comment by DavertMik** [comment]
Well, I like it. Please merge when you feel it is ready.

**Comment by DavertMik** [comment]
Btw, thanks for `clientRequest`, I will use it for making a hidden method so users could send various requests from Helpers: https://github.com/Codeception/Codeception/issues/2319

**Comment by Naktibalda** [comment]
I have a problem here - BrowserKit Client does not provide getters for followRedirects and maxRedirects properties. maxRedirects is private so even extending Client is not a solution.

I will make a pull request to add getters, but I don't have much hope that it will accepted.

**Comment by DavertMik** [comment]
Thanks. Let's have it

**Pull request merged**
