### PR TITLE
added dontSeeInPopUp function

### PR DESCRIPTION
**Pull request by kpascal**
this is in reference to issue https://github.com/Codeception/Codeception/issues/4588

### CODE REVIEW

**Comment by DavertMik** [comment]
Please fix that failing test with quotes:

> tests/web/WebDriverTest.php:testFailedDontSeeInPopup
Failed asserting that exception message 'Failed asserting that 'Really?' does not contain "Really?".' contains 'Failed asserting that 'Really?' contains "Really?"'.

and we are done :)

**Comment by kpascal** [comment]
I believe it was failing because of the $alert->dismiss(); let me know if that really needs to be there?

**Comment by DavertMik** [comment]
According to the message the reason is different.

> I believe it was failing because of the $alert->dismiss();

No it's really important to do something with alert. Consider a situation when test finishes with an open popup. A next test won't be able to handle new browser session as popup will be visible

**Comment by nshelms** [comment]
I'm trying to help @kpascal with this PR but i'm having trouble running the tests locally.  We've added the function into WebDriver module, but when running `codecept run web WebDriverTest:testDontSeeInPopup` I'll get an error saying that Webdriver::dontSeeInPopup is undefined when in fact it is defined inside WebDriver module. I've already ran `codecept build` manually but it does not add any additional methods into the generated helpers. Even manually adding the references inside WebGuyActions isn't working. Any thoughts?

**Comment by kpascal** [comment]
in the event the text is seen while using dontSeeInPopUp, the test will automatically die because its prefixed with 'dont' therefore not allowing the test to continue, killing the session and killing the popup

**Comment by DavertMik** [comment]
> in the event the text is seen while using dontSeeInPopUp, the test will automatically die because its prefixed with 'dont' therefore not allowing the test to continue, killing the session and killing the popup

A test will but process won't. Browser also won't be closed. Esp if you reuse browser session.
Also, this method can be used as `cantSeeInPopup` so it won't stop on failure. 
You see, lots of cases

**Comment by DavertMik** [comment]
Hey, looks like you are "First-time GitHub contributor" 
Congratulations on first merged pull request! :balloon:

**Pull request merged**
