### PR TITLE
hiding Symfony 4.3 deprecation warning

### PR DESCRIPTION
**Pull request by DavertMik**
Let's hide this annoying message as this has no deal to Codeception users

### CODE REVIEW

**Comment by s1mple** [comment]
Wow, thank you so much! This was annoying me so much, and now you fixed it. 🙇

**Comment by DanielRuf** [comment]
No difference. I guess it affects the whole Codeception framework. See https://github.com/Codeception/Codeception/search?q=dispatch%28&unscoped_q=dispatch%28

**Comment by Naktibalda** [comment]
@DanielRuf This change hadn't been release yet.
Also I noticed that you use Codeception v2 which won't be patched.

**Comment by DanielRuf** [comment]
> Also I noticed that you use Codeception v2 which won't be patched.

Sure but we tried it and it definitely does not fix the regression caused by `symfony/event-dispatcher > 4.2.8`.

**Comment by fernandojmartin** [comment]
I'm on version 4 and still got that annoying message: one per test.
Am I doing anything wrong?
```
$ php vendor/bin/codecept init upgrade4
 Welcome to Codeception v4 Upgrade wizard!

Codeception is maintained since 2011, is free & open-source.
To make it better we need your feedback on it!

Please take a minute and fill in a brief survey:
http://bit.ly/codecept-survey

? Did you fill in the survey? (y/n) y
Thank you! 
 No upgrade needed! Everything is fine already 
```
`$ composer show` (just the relevant parts)
```
codeception/codeception             4.0.1              BDD-style testing framework
codeception/lib-asserts             1.1.1              Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser        1.2.3              Parent library for all Codeception framework modules and PhpBrowser
codeception/module-asserts          1.1.1              Codeception module containing various assertions
codeception/module-db               1.0.1              WebDriver module for Codeception
codeception/module-phpbrowser       1.0.0              Codeception module for testing web application over HTTP
codeception/module-rest             1.0.0              REST module for Codeception
codeception/phpunit-wrapper         7.8.0              PHPUnit classes used by Codeception
codeception/stub                    3.0.0              Flexible Stub wrapper for PHPUnit's Mock Builder
...
...
symfony/browser-kit                 v5.0.2             Symfony BrowserKit Component
symfony/cache                       v4.3.4             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts             v1.1.5             Generic abstractions related to caching
symfony/config                      v4.3.4             Symfony Config Component
symfony/console                     v4.3.3             Symfony Console Component
symfony/css-selector                v5.0.2             Symfony CssSelector Component
symfony/debug                       v4.3.4             Symfony Debug Component
symfony/dependency-injection        v4.3.4             Symfony DependencyInjection Component
symfony/dom-crawler                 v5.0.2             Symfony DomCrawler Component
symfony/dotenv                      v4.3.4             Registers environment variables from a .env file
symfony/event-dispatcher            v4.3.4             Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v1.1.5             Generic abstractions related to dispatching event
symfony/filesystem                  v4.3.4             Symfony Filesystem Component
symfony/finder                      v4.3.4             Symfony Finder Component
symfony/framework-bundle            v4.3.4             Symfony FrameworkBundle
symfony/http-client                 v5.0.2             Symfony HttpClient component
symfony/http-client-contracts       v2.0.1             Generic abstractions related to HTTP clients
symfony/http-foundation             v4.3.4             Symfony HttpFoundation Component
symfony/http-kernel                 v4.3.4             Symfony HttpKernel Component
symfony/inflector                   v4.3.4             Symfony Inflector Component
symfony/mime                        v4.3.4             A library to manipulate MIME messages
symfony/monolog-bridge              v4.3.4             Symfony Monolog Bridge
symfony/monolog-bundle              v3.4.0             Symfony MonologBundle
symfony/options-resolver            v4.3.4             Symfony OptionsResolver Component
symfony/polyfill-ctype              v1.12.0            Symfony polyfill for ctype functions
symfony/polyfill-iconv              v1.12.0            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn           v1.12.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring           v1.12.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php56              v1.12.0            Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70              v1.12.0            Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72              v1.12.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73              v1.12.0            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-util               v1.12.0            Symfony utilities for portability of PHP codes
symfony/process                     v4.3.4             Symfony Process Component
symfony/property-access             v4.3.4             Symfony PropertyAccess Component
symfony/routing                     v4.3.4             Symfony Routing Component
symfony/service-contracts           v1.1.6             Generic abstractions related to writing services
symfony/stopwatch                   v4.3.4             Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.8             Symfony SwiftmailerBundle
symfony/translation                 v4.3.4             Symfony Translation Component
symfony/translation-contracts       v1.1.6             Generic abstractions related to translation
symfony/var-exporter                v4.3.4             A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/workflow                    v4.3.4             Symfony Workflow Component
symfony/yaml                        v4.3.4             Symfony Yaml Component

```

**Comment by Naktibalda** [comment]
Which message?

The only odd thing about your dependencies is that you use 5.0 of browser-kit and http-client, but 4.3 version of other Symfony components. Can you upgrade them to 5.0?

**Comment by fernandojmartin** [comment]
Thanks for the quick response!

The message:
```
...
Time: 588 ms, Memory: 16.00 MB

OK (3 tests, 6 assertions)
{
    "statusCode": 500,
    "errors": [
        {
            "type": "SERVER_ERROR",
            "description": "ERROR: Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. on line 58 in file \{...}\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php."
        }
    ]
}{
    "statusCode": 500,
    "errors": [
...
```
I'm unsure about upgrading as `dispatch()` is used in many places in the project. Should check with other devs if an upgrade doesn't brakes anything else.
However I see it should be fixed the annoying message thing. I don't know what could be failing.

Should I downgrade browser-kit and http-client ?

**Comment by Naktibalda** [comment]
I have no idea how you get that JSON after OK line.

If all you want is to hide deprecation messages, lookup how to set Symfony PHPUnit bridge environment variable and set it to 'weak'.

**Comment by Naktibalda** [comment]
You can use  `SYMFONY_DEPRECATIONS_HELPER=weak codecept run functional` or
```sh
export SYMFONY_DEPRECATIONS_HELPER=weak
codecept run functional
```

`weak` and `disabled` values are documented at https://symfony.com/doc/4.2/components/phpunit_bridge.html#making-tests-fail

These values still work with 4.3, but phpunit-bridge deprecation helper became much more configurable (and complicated) in 4.3: https://symfony.com/doc/4.3/components/phpunit_bridge.html#making-tests-fail

**Comment by fernandojmartin** [comment]
Thanks Gintautas for your support.

Unfortunately the message is still there.
I tried with Birdge 5.0, 4.4.2, then 4.3.0 and got an incompatibility with other packages when trying to go to 4.2.
The error message only changes when I forcedly set an unknown value in the config.

I'll evaluate upgrading EventDispatcher.

Thanks anyway.

**Comment by fernandojmartin** [comment]
Hey Gintautas, I'm back.
Forget about the DEPRECATIONS HELPER.

I wanted to show you this; it's a trace from the error in Symfony's `EventDispatcher:57` (in the place the error is thrown)

```
Symfony\Component\EventDispatcher\EventDispatcher->dispatch > .../vendor/codeception/phpunit-wrapper/src/DispatcherWrapper.php:25
Codeception\PHPUnit\ResultPrinter\UI->dispatch  > .../vendor/codeception/phpunit-wrapper/src/ResultPrinter/UI.php:32
Codeception\PHPUnit\ResultPrinter\UI->printDefect  > .../vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:345
```

**Pull request merged**
