### PR TITLE
Env merging and config files

### LINKED ISSUE #1746: Environments merging and configuration files
For more complex projects with multiple environments and running contexts (like many WebDriver browsers), environment configuration is quite cumbersome as it requires creating separate environment for each settings combination.

Possibility to merge multiple environments into one configuration would be great:

```bash
$ php codecept.phar run acceptance --env dev,phantom --env dev,chrome --env dev,firefox
```

In addition, to avoid main configuration file to grow too much and to make the structure a bit cleaner, we could provide option to put environment-specific settings into its own file.

### PR DESCRIPTION
**Pull request by sjableka**
Closes #1746 

**Merging:**
It's possible to merge multiple environments into one configuration by using comma as a separator:

```bash
$ php codecept.phar run acceptance --env dev,phantom --env dev,chrome --env dev,firefox
```

Configuration is merged in the given order. This way you can easily create multiple combinations of your environment configurations.

**Configuration files**
You can define environments in separate configuration files placed in the directory specified by `envs` option in
`paths` configuration:

```yaml
paths:
    envs: tests/_envs
```

Names of these files are used as environments names (e.g. `chrome.yml` or `chrome.dist.yml` for environment named `chrome`)
and in there you can just specify options that you wish to override:

```yaml
modules:
    config:
        WebDriver:
            browser: 'chrome'
```

Environment configuration files are merged into the main configuration before suite configuration is merged.

### CODE REVIEW

**Comment by DavertMik** [comment]
Looks my recent changes broke this PR. I'm doing refactoring with removal of static properties of SuiteManager, so architecture is changing a bit. Could you merge the master branch and resend this PR? 
Thanks

**Comment by sjableka** [comment]
@DavertMik Merged the master.

**Comment by DavertMik** [comment]
Thanks!

**Comment by younes0** [comment]
what about taking `.env` settings?

**Comment by Faiyaz** [comment]
@sjableka: Can you please take a look at this question on StackOverflow and see if you can answer http://bit.ly/1JR3xc0.

I am unable to get tests/_env directory to load custom env files. My tests always end up loading the default config even when I pass --env myenv.yml when run acceptance test. What am i missing?

**Comment by sjableka** [comment]
@Faiyaz Please see https://github.com/Codeception/Codeception/issues/2229#issuecomment-128947184

**Comment by Faiyaz** [comment]
Thanks @sjableka.

**Pull request merged**
