### PR TITLE
Added some useful methods, with tests

### PR DESCRIPTION
**Pull request by antoniofrignani**
Added methods: 
**grabCollectionCount**: _returns the documents count in a collection, possible to filter by criteria_
**seeElementIsArray** and **seeElementIsObject**: _useful to check that an element in a document has the correct type_

### CODE REVIEW

**Comment by antoniofrignani** [comment]
The tests reports all ok, i think the errors in Travis are coming from other modules
schermata 2015-01-15 alle 11 24 21

**Comment by DavertMik** [comment]
Hi, thanks, this PR looks really useful. 
I will only ask you to stick with defaults: use `grab` prefix for methods that return value and `see` prefix for assertions.

**Comment by antoniofrignani** [comment]
Ok, i think it should be ok now. I added other tests to verify Exceptions. 

Side question: is there any coding-style guide for Codeception modules? It seems that i can't find it...

**Comment by DavertMik** [comment]
> Side question: is there any coding-style guide for Codeception modules? It seems that i can't find it...

PSR-2 if you mean this as coding style...
For `grab`, `see` it is common convention described in README of modules dir

Thanks for nice improvements!

**Comment by antoniofrignani** [comment]
Thank you Michael, the README was the one i wanted. Another thing is: i have to update the documentation or it is somewhat automatically generated? If yes, should i Update it in the `docs` directory of the 2.0 branch or directly in the `docs` branch?

**Comment by DavertMik** [comment]
@antoniofrignani docs are generated from PHP docblocks, so you are done well. Nothing more is required. Thanks!

**Pull request merged**
