### PR TITLE
0 < exit-state <= 125

### PR DESCRIPTION
**Pull request by imme-emosol**
https://github.com/Codeception/Codeception/discussions/6330

### CODE REVIEW

**Comment by imme-emosol** [comment]
Some extra information there might not hurt either ?
Maybe when running codecept with --debug and/or -vvv ?

**Comment by Naktibalda** [comment]
> Some extra information there might not hurt either ?

Usual causes for this exit is `die()` or `exit` in application code (I'm not aware of any other causes).
There is no way to tell where in the code it happened.

The code is definitely in a broken state and you can't know if failing test could pass or fail on that run.

**Comment by Naktibalda** [comment]
Code which exists in untestable, so `125` would be appropriate.

**Comment by imme-emosol** [comment]
Might be caused by my setting of `xdebug.halt_level=E_WARNING|E_NOTICE|E_USER_WARNING|E_USER_NOTICE` though.. So that might be an exceptional case.

**Comment by Naktibalda** [comment]
yes, don't use it.

**Comment by imme-emosol** [comment]
Confirmed :)

Okay, so this _should_ only be caused by exit/die.
Would it be possible to show where that exit/die happened when --debug and/or -vvv is given to codecept run ?

**Comment by Naktibalda** [comment]
If it was possible, we would do it.

**Comment by Naktibalda** [comment]
For the record, the reason for using 255 as exit code:

> 255 is the code used by uncaught exception, so I retained the same number.

**Comment by Naktibalda** [comment]
Please update https://github.com/Codeception/Codeception/blob/5.0/tests/cli/ErrorHandlerCest.php

**Comment by TavoNiievez** [comment]
Is it okay for this to target `5.0` ?

**Comment by Naktibalda** [comment]
> Is it okay for this to target `5.0` ?

Fine with me. It makes exit code a bit more useful, but it doesn't look like a bugfix to me.

**Review by TavoNiievez — APPROVED** [review]

**Review by DavertMik — APPROVED** [review]

**Pull request merged**
