### PR TITLE
fix redirect when base url has path

### PR DESCRIPTION
**Pull request by tiger-seo**

### CODE REVIEW

**Comment by Naktibalda** [comment]
Why does it fail on PHP 5.4?

**Comment by Naktibalda** [comment]
ok, the answer is obvious - because you made your change in Guzzle6 connector. Could you make the same change in Guzzle connector?

**Comment by Naktibalda** [comment]
Codeception does not follow regular absolute path rules.
If the path starts with / it should replace path set in base_uri instead of being appended.

**Comment by tiger-seo** [comment]
> Codeception does not follow regular absolute path rules.
> If the path starts with / it should replace path set in base_uri instead of being appended.

good catch :)

**Comment by DavertMik** [comment]
> If the path starts with / it should replace path set in base_uri instead of being appended.

I'm not sure here but what about If we have url:

```
http://site.com/api/v1
```

and we'd like to get users there, then we should be able to use 

```
sendGET('/users')
```

I think a similar example can be provided for PHPBrowser as well. Like accessing `/users` for 

```
http://site.com/blog
```

should move us to 

```
http://site.com/blog/users
```

**Comment by DavertMik** [comment]
@tiger-seo you can skip this test for old Guzzle. Please use `skipForOldGuzzle` method

**Comment by Naktibalda** [comment]
Please don't abandon PHP 5.4, I'm stuck with it for another year at least

**Comment by DavertMik** [comment]
@Naktibalda that's terrible :(
@tiger-seo ok, so could you get it implemented for Guzzle v.5? You can downgrade Guzzle in your composer.json

**Comment by tiger-seo** [comment]
@DavertMik i thought the scope of
> If the path starts with / it should replace path set in base_uri instead of being appended.

is only redirects

**Comment by Naktibalda** [comment]
Link clicks and forms should behave in the same way. Test code like amOnPage and sendPOST can keep current behaviour for BC. We need to support <base> tags.

**Comment by Naktibalda** [comment]
Base tags

**Comment by DavertMik** [comment]
> Link clicks and forms should behave in the same way.

yeah, you are right. 

But what do you mean about base tags?

**Comment by Naktibalda** [comment]
https://developer.mozilla.org/en/docs/Web/HTML/Element/base

**Comment by tiger-seo** [comment]
@DavertMik i've done fix for the old guzzle

**Comment by JarJak** [comment]
Happened to me with PHP 5.6 and latest Codeception / Guzzle 6.0. See: https://github.com/Codeception/Codeception/issues/2402

**Comment by tiger-seo** [comment]
@Naktibalda  @DavertMik  fixing the issue with absolute urls globally would be a major BC break, so for now my suggestion would be to fix only this problem
What's your take on this, guys ?

**Comment by JarJak** [comment]
:+1: fixed my issue

**Comment by Naktibalda** [comment]
That's fine with me.

**Comment by DavertMik** [comment]
thanks

**Pull request merged**
