### PR TITLE
Db test refactoring

### PR DESCRIPTION
**Pull request by Naktibalda**
I refactored SqliteTest and PostgresTest to be more in line with MysqlTest:
Moved initial setup to setUpBeforeClass, 
load to setUp, 
cleanup to tearDown.

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks, looks good. Waiting to get everything green there )

**Comment by samdark** [comment]
Seems that it broke things...

**Comment by Naktibalda** [comment]
It works for me! At least the DbTest.

**Comment by DavertMik** [comment]
Looks like an issue with loading dump before the test. To be honest most of Db tests do not work for me, as I don't setup PostgreSQL or MySQL locally, instead I rely on Travis ) 

Please do not hurry, but could you find what goes wrong there?

**Comment by Naktibalda** [comment]
I will create a separate branch for debugging which will run DbTest only

**Comment by Naktibalda** [comment]
DbTest was green when executed in isolation: https://travis-ci.org/Codeception/Codeception/builds/64602009

**Comment by Naktibalda** [comment]
I reproduced this test locally by running SqliteTest and DbTest in a group.

[Groups] debug 

Unit Tests (654) ---------------------------------------------------------------------------------------------------------------------------
SqliteTest::testCleanupDatabase                                                                                                       Ok
SqliteTest::testLoadDump                                                                                                              Ok
DbTest::testSeeInDatabase                                                                                                             Error
DbTest::testDontSeeInDatabase                                                                                                         Error
DbTest::testDontSeeInDatabaseWithEmptyTable                                                                                           Error
DbTest::testGrabFromDatabase                                                                                                          Error
DbTest::testHaveAndSeeInDatabase                                                                                                      Error
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Naktibalda** [comment]
I solved the issue by changing dsn in DbTest to avoid conflicts with SqliteTest.

**Comment by Naktibalda** [comment]
Adding this line fixed appveyor. Why does it work for other branches?
  - echo extension=php_pdo_sqlite.dll >> php.ini

**Comment by Naktibalda** [comment]
Appveyor holds a grudge against me.


Start-Service : Failed to start service 'postgresql-x64-9.3 (postgresql-x64-9.3)'.

**Pull request merged**
