### PR TITLE
Merge changes from 4.1 branch to 5.0

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by TavoNiievez** [comment]
btw, what does it take to completely remove the Cept format?
As I understood in Codeception 5 this deprecation would be effective.

**Comment by Naktibalda** [comment]
Delete src/Codeception/Test/Cept.php, src/Codeception/Test/Loader/Cept.php and GenerateCept command.

**Comment by TavoNiievez** [comment]
Well... no idea why it keeps failing :)

**Comment by TavoNiievez** [comment]
[`GuzzleHttp\Psr7\Uri`](https://github.com/guzzle/psr7/blob/148492f9e2e1524317a8aa60875f5b59517a9374/src/Uri.php#L132) implements the magic method `__toString()`...
maybe [`mergeUrls`](https://github.com/Codeception/Codeception/blob/60c9ed971d4bae7328dde7fd44829b1f849403ab/src/Codeception/Util/Uri.php#L29) should remove `string` typing in method signature and cast `(string)` internally.

**Comment by Naktibalda** [comment]
One day we will be able to use [stringable](https://www.php.net/stringable) typehint.

**Review by TavoNiievez — APPROVED** [review]

**Comment by Naktibalda** [comment]
string typehint can come back,
you removed casting to string in https://github.com/Codeception/module-phpbrowser/pull/12/files#diff-7089ef726bcb6e8e53ee0dc3317f15ff81fb7a999ae214323435a29f46c19649L175 
so I raised https://github.com/Codeception/module-phpbrowser/pull/14 to put it back.

**Comment by TavoNiievez** [comment]
ahh ok, no problem

**Review by TavoNiievez — APPROVED** [review]

**Pull request merged**
