### PR TITLE
Bugfix groups by directory

### PR DESCRIPTION
**Pull request by kimvladis**
Bugfix issue #2550
Replaces double slash by one.

### CODE REVIEW

**Comment by Naktibalda** [comment]
Thanks @kimvladis 

@DavertMik Why are these double slash issues happening all over the place?

**Comment by DavertMik** [comment]
Thanks!

> Why are these double slash issues happening all over the place?

Looks like  it is related to Symfony Finder. I didn't have chance to investigate this deeper

**Comment by kimvladis** [comment]
@DavertMik yes it is. Symfony Finder adds one excess slash when concat $rootPath and $filePath. Seems to bug in Symfony Finder.

**Comment by VoidWalker** [comment]
Looks like there is a rework, guys
The fix is good for Unix systems, but fro Windows, where there is a backward slashes, it doesn't
Path still has double slashes after preg_replase:
D:\autotests\projects\uv-fashions-autotests\tests\acceptance\\LoginCest.php

As a meantime workaround you may specify path to tests like:
groups:
    custom: [tests/acceptance//LoginCest.php:loginLogout]

d__autotests_projects- _codecept phar_src_codeception_lib_groupmanager php - phpstorm 10 0 1 2015-12-29 11 34 00

**Pull request merged**
