### PR TITLE
Location header only redirects when status code is 3xx

### LINKED ISSUE #3171: On POST creation, 201 status with a Location header should not fail
In the case of a POST interaction, `InnerBrowser` is aggressively evaluating a redirection response header, and evaluating a response as a failure if the browser is not redirected.

In this particular case, a _Location_ header doesn't indicate a redirection, but instead indicates the location of the created record (defined in boring detail in [RFC2616, 10.2.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2)).

Would there be other issues I'm not seeing by also checking for an HTTP status code of 201 and not interpreting the Location header as a redirect? Even better than that, check for no status code or a [`3xx`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) code and then evaluate the purpose of the header?

As a side note, `2.2.1` sees the issue, but `2.1.10` does not.

### PR DESCRIPTION
**Pull request by Naktibalda**
Fixes #3171

### CODE REVIEW

**Comment by DavertMik** [comment]
With tests! Nice

**Comment by stipsan** [comment]
We just upgraded to 2.2 and our entire testing suite failed due to our REST api returning a location header on every 2xx request.
Updated to latest 2.2 few hours ago but it's missing this fix, @DavertMik any chance there's a new 2.2 release out soon?

**Comment by torkiljohnsen** [comment]
Our team also have this issue :) This needs to be merged into 2.2 ASAP. REST APIs will return a `Location` header when a resource is created (and a `201 created` is returned), but right now this results in a redirect. Yikes.

Also: CodeCeption 2.2 Laravel5 module has [a lot of breaking changes](https://github.com/Codeception/Codeception/pull/2866) that are not listed in [the changelog](http://codeception.com/changelog).

**Comment by sureshHARDIYA** [comment]
I am facing the same issue. Need Fix ASAP with this thing. Embarrassing  !!!

**Comment by Naktibalda** [comment]
I would like to use this opportunity to invite you guys to test the release candidate next time.

**Pull request merged**
