### PR TITLE
[WIP] Yii2 log handling

### PR DESCRIPTION
**Pull request by SamMousa**
- [X]  Mock `register_shutdown_function` in `yii\log` namespace.
- [X]  Provide new log target for routing logs to Codeception debug.

- [ ] Don't override `Yii::$logger`, this means configured loggers will run normally during tests, unless the user uses a different configuration.

I think the last one is better because it allows people to test their log configuration and it reduces difference between test setup and production setup.

### CODE REVIEW

**Comment by schmunk42** [comment]
Will this also go into 2.x or is development limited there?

**Comment by SamMousa** [comment]
@schmunk42 I prefer to spend my time on the newest version (I have updated my applications to use this version as well).
If you have Yii troubles with 3.0 ping me on slack, or alternatively, when this get merged feel free to create a new PR based on it for 2.x

**Comment by Naktibalda** [comment]
Please raise a new pull request to https://github.com/Codeception/module-yii2

**Comment by SamMousa** [comment]
Will do.

**Pull request closed without merging**
