### PR TITLE
match title in input fields

### PR DESCRIPTION
**Pull request by gimler**
Make it possible to click on a input by title. For example when you have a form input with only a font icon.

```
<input type="submit" class="btn btn-success" value="&#xf011;" title="Login" />
```

<a class="jsbin-embed" href="http://jsbin.com/bevotayuga/1/embed?html,css,output">JS Bin on jsbin.com</a>

### CODE REVIEW

**Comment by gimler** [comment]
@DavertMik we cannot change the application for that ;(

title is a global attribute see
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by DavertMik** [comment]
> title is a global attribute see

Ah, ok. Then could you update the same XPath for InnerBrowser for internal compatibility?
Then I'm merging.

**Comment by gimler** [comment]
@DavertMik i am not shure where to do this. i think `InnerBrowser.php::369` is the correct place but `selectButton()`is a method from symfony/dom-crawler.

**Comment by DavertMik** [comment]
Oh, yes. Looks like it's impossible then (
Ok, let's have it this way.

**Pull request merged**
