### PR TITLE
Fix marking test incomplete

### PR DESCRIPTION
**Pull request by JarJak**
https://github.com/Codeception/Codeception/issues/2702

### CODE REVIEW

**Comment by Naktibalda** [comment]
Please make a pull request to 2.1 branch instead.

**Comment by DavertMik** [comment]
Thanks. That's important. Somehow I missed to change it for 2.1 branch. I pushed this fix by myself, thanks for pointing to it.

**Comment by JarJak** [comment]
@DavertMik I can't see any change here: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/PHPUnit/Listener.php

**Comment by JarJak** [comment]
@DavertMik ?

**Pull request closed without merging**
