### PR TITLE
Removed factory-muffin from composer.json

### PR DESCRIPTION
**Pull request by Naktibalda**
Because DataFactory module has no tests

### CODE REVIEW

**Comment by Naktibalda** [comment]
Laravel tests failed.
I think that these dependencies should be added to Laravel test app as documented in documentation of DataFactory module.

**Comment by Naktibalda** [comment]
Actually it is a missing dependency of Lumen app which doesn't even use DataFactory module:

```
1) AuthCest: Authenticate with api token
 Test  tests/functional/AuthCest.php:authenticateWithApiToken
                                           
  [Error] Class 'Faker\Factory' not found  
                                           
Scenario Steps:
 1. $I->have("App\User") at tests/functional/AuthCest.php:9
#1  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/database/DatabaseServiceProvider.php:67
#2  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/container/Container.php:746
#3  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/container/Container.php:644
#4  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/laravel/lumen-framework/src/Application.php:212
#5  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/database/DatabaseServiceProvider.php:71
#6  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/container/Container.php:746
#7  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/illuminate/container/Container.php:644
#8  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/laravel/lumen-framework/src/Application.php:212
#9  /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/laravel/lumen-framework/src/helpers.php:39
#10 /home/travis/build/Codeception/Codeception/frameworks-lumen/vendor/laravel/lumen-framework/src/helpers.php:200
```

**Comment by DavertMik** [comment]
Nice. Could we place this fork under Codeception organization? Let me check you have rights to create and manage the repo... Ok, now you have them ) Please move the fork

**Comment by DavertMik** [comment]
Great!

**Pull request merged**
