### PR TITLE
[Symfony] Minimal support for Symfony Flex directory and namespace str.

### PR DESCRIPTION
**Pull request by VolCh**
Introduce support of Symfony Flex - Symfony 3.3+ recommended way for Symfony app.
Demo app can be found at https://github.com/VolCh/symfony-flex-demo

### CODE REVIEW

**Comment by Naktibalda** [comment]
Please change target branch to 2.3 and rebase your changes on it.
It will fix MongoDb errors on Travis, but you may still need to check why your code is failing to find AppKernel in my test site.

**Comment by DavertMik** [comment]
Awesome, just what we need!
Thanks, @VolCh

**Comment by DavertMik** [comment]
Cool, I think I can change the base branch. But tests still should be restarted

**Comment by VolCh** [comment]
I rebased and fixed Symfony AppKernel issue - switched to getRealpath from getFilename.

**Comment by DavertMik** [comment]
Nice! 
Do you know if there is a Symfony Flex demo project so we could try to run some tests on it?

**Comment by VolCh** [comment]
I couldn't found any enough complex (at least with some doctrine entities and custom services) demo  project and have started my own. I'm going to test routing and doctrine integration in this week as soon as setup 5.6 env.

**Pull request merged**
