### PR TITLE
Set upper boundary of supported PHPUnit versions to <5.4

### PR DESCRIPTION
**Pull request by Naktibalda**
PHPUnit 5.4 is likely to break Codeception\Util\Stub, so I'm setting this restriction to prevent automatic upgrade to PHPUnit 5.4

I will revisit this issue in June when PHPUnit 5.4 is released.

### CODE REVIEW

**Comment by Naktibalda** [comment]
#2986

**Comment by DavertMik** [comment]
This should not affect users that are not using `Codeception\Util\Stub`. So I'm against setting upper boundary. What we can do is to throw an exception with a hint to downgrade to PHPUnit v5.3 in class. And update the changelog

**Comment by Naktibalda** [comment]
It won't do much harm if the users will not be able to upgrade to Phpunit 5.4 for a week. But if someone really want it, they could use the penultimate version of Codeception which has no restriction.

There is a risk and I think that it would be safer to put a restriction. But if you disagree, then we can do nothing and see how it works out.

**Comment by DavertMik** [comment]
Oh, what a mess there in `Codeception\Util\Stub` :(

**Comment by DavertMik** [comment]
The most nice change I see in PHPUnit 5.4 is this method https://github.com/sebastianbergmann/phpunit/blob/master/src%2FFramework%2FTestCase.php#L1407

**Comment by Naktibalda** [comment]
So we actually needed it.

**Comment by DavertMik** [comment]
Yes :(
Actually the only change which really affected us was not in PHPUnit itself but in PHPUnit Code overage :(

**Pull request closed without merging**
