### PR TITLE
Updated Memcache::seeInMemcached

### PR DESCRIPTION
**Pull request by sergeyklay**
* Updated `Memcache::seeInMemcached` to check if the key exists alone or with the desired value
* Added `Memcache::haveInMemcached`
* Fixed `Memcache::dontSeeInMemcached`

### CODE REVIEW

**Comment by DavertMik** [comment]
I will need detailed description to put into changelog. Or you can update changelog by yourself :)

**Comment by sergeyklay** [comment]
@DavertMik done

**Comment by sergeyklay** [comment]
@DavertMik Latest change fixes the issue with message

> Failed asserting that false is not equal to false.

because memcached **can** return false

**Comment by DavertMik** [comment]
Thanks

**Pull request merged**
