### PR TITLE
typo in service name

### PR DESCRIPTION
**Pull request by bscheshirwork**
use "codecept" above

#3745

### CODE REVIEW

**Comment by DavertMik** [comment]
@schmunk42 is that ok?

**Comment by schmunk42** [comment]
Yes, but it depends a bit on the final decision of https://github.com/Codeception/Codeception/pull/3739#issuecomment-261810192

In the current image there's a default entrypoint for `codecept` which makes commands a bit shorter to type. In the related issue, there's a discussion about changing that to `bash`.

Any thoughts about https://github.com/Codeception/Codeception/pull/3739#issuecomment-263076079? Would there be other commands than `codecept` to use from the image?

**Comment by Faryshta** [comment]
this is the reason all the pr tests are failing?

**Comment by Naktibalda** [comment]
If this change is still necessary please raise a new pull request to 2.3 branch.

**Pull request closed without merging**
