### PR TITLE
Require phpunit/phpunit ~5.0.0

### PR DESCRIPTION
**Pull request by kornrunner**
PHPUnit 5.0 is the current stable release series.

So, composer.json is updated:
- bump phpunit to ~5.0.0
- bump php to >=5.6.0 (due to phpunit)

### CODE REVIEW

**Comment by GawainLynch** [comment]
In a stable branch?

**Comment by kornrunner** [comment]
You're right, it's a breaking change. I don't mind sending another PR, I guess this should go to 3.0? However, I don't see that branch (and I don't know the plans)

**Comment by GawainLynch** [comment]
Hehe… I am "just a consumer" and my comment sounded a bit rude re-reading it… I have not place to sound like that. Humble appolgies!

**Comment by DavertMik** [comment]
It's not that easy to update to PHPUnit, at least current builds won't pass  https://travis-ci.org/Codeception/Codeception/jobs/84162586
We will update to it once we feel we are ready for it. 

Actually, just wondering, is there any particular feature of PHPUnit 5.0 you want to upgrade for?

**Comment by devinfd** [comment]
+1 to this.
I need to use assertObjectHasAttribute https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertObjectHasAttribute which was introduced in version 5

**Pull request closed without merging**
