### PR TITLE
Fix for issue 1828

### PR DESCRIPTION
**Pull request by lowerends**
This fixes issue #1828 and also gets rid of the defaults loop in the submitForm() function.

### CODE REVIEW

**Comment by zbateson** [comment]
Thanks for the PR @lowerends .

There are some Travis errors for FrameworkTest and PhpBrowserTest - could you look into them please?  It may be easier to run the tests for those two modules locally.  Have a look at https://github.com/Codeception/Codeception/blob/2.0/tests/README.md

**Comment by lowerends** [comment]
The tests for FrameworkTest and PhpBrowserTest are running fine locally (no errors). Am I merging to the correct branch?

As for the order of merging the values, my first commit is giving trouble when using ```uncheckOption()```, while it's working fine with the second commit. I'm looking into that now. Any ideas what could cause this? The same queryParams are submitted, but in a different order.

**Comment by zbateson** [comment]
Hmm, I can't explain why the tests would work for you locally.  Applying your PR as a patch and running tests for PhpBrowser and FrameworkTest locally give me 10 errors.

A quick glance at the errors tells me there are probably a few issues:

1 - the order of params would cause the defaults on the page to be sent, rather than what is sent via $params parameter
2 - checkbox values are a special case for booleans at least, see ```setCheckboxBoolValues``` but I'm not sure this is the issue... I'd have to dig a bit deeper
3 - submit button values are probably not included in what's returned by ```getValues()``` - I'm not sure there's a way to get the value of a submit button from the returned form object returned by ```getFormFor()``` for the $button parameter - if not, may need to get it with $form->filter()

Thanks for all the effort.

**Comment by lowerends** [comment]
Ok, I managed to get the tests failing now (was testing on the wrong branch). There's a couple of issues indeed which don't seem to be that easy to solve. Before digging deeper, I'd like to take one step back at the problem that we're trying to solve here, which is adding fields to the POST data. 

I would like to repeat my former question about adding a ```addField()``` method which would allow to add POST data via ```addField($key, $value)```. This would actually allow to simulate Javascript added fields to a form. Would such a function make sense?

I'll also have a deeper look at the problems I have with boolean checkboxes.

**Comment by lowerends** [comment]
A possible extension would then of course be to have a ```deleteField()``` as well, which would allow to remove POST data from the form. This could then be used to simulate a Javascript delete action on a form field.

**Comment by zbateson** [comment]
No worries - thanks for checking :)

You can already send POST data without relying on addField using submitForm - you can pass any data you like in the second argument and it'll be posted:

```php
$I->submitForm('#my-form', ['some-non-existent-field' => 'some value']);
```

**Comment by lowerends** [comment]
Thanks for your feedback.

The problem I have with ```submitForm()``` is that it requires you to add *all* the data to the ```$params``` array, as the ```$params``` array replaces all the form values. So you can't use ```fillField()``` anymore.

**Comment by zbateson** [comment]
That is true I fully agree, however if this PR is fixed and merged fillField will be usable for exactly that scenario :+1: 

Actually $params doesn't replace all form values, it's just incompatible with fillField at the moment.  In other words, it takes default values set on the form when the page was loaded but not those added with fillField.

**Comment by zbateson** [comment]
This would also affect #1689

**Comment by zbateson** [comment]
Hi @lowerends - please check out #1840 - was a bit more of a change than expected :)

**Comment by DavertMik** [comment]
closed in favor of #1840

**Comment by lowerends** [comment]
@zbateson thanks! This looks great. I was looking into it myself as well but had some other work popping up in between. Thanks for the great improvement!

**Pull request closed without merging**
