### PR TITLE
Fix for output string length

### PR DESCRIPTION
**Pull request by mkudenko**

### CODE REVIEW

**Comment by Naktibalda** [comment]
The change looks like the right thing to do.
But could you describe what issue does it fix?

**Comment by mkudenko** [comment]
The issue is that the output string is being cut off when using data providers.

Before:
screenshot from 2015-10-18 22 07 42

After:
screenshot from 2015-10-18 22 08 04

**Comment by Naktibalda** [comment]
What kind of tests produce such output?

**Comment by mkudenko** [comment]
Those are PSR-4 namespaced PHPUnit tests.

**Comment by Naktibalda** [comment]
I am asking, because I raised this issue: https://github.com/Codeception/Codeception/issues/2334

I created this PhpUnit test now:
```
class dataProvidersTest extends \PHPUnit_Framework_TestCase
{
    public function provideData()
    {
        return [
            ["aaa"],
            ["bbb"],
            ["ccc"],
        ];
    }

    /**
     * @dataProvider provideData
     */
    public function testMe($a)
    {
    }
}
```

and got this output:
```
Experiment Tests (1) ------------------------
dataProvidersTest::testMe | #0         Ok
dataProvidersTest::testMe | #1         Ok
dataProvidersTest::testMe | #2         Ok
---------------------------------------------
```

It doesn't look like yours.

**Comment by mkudenko** [comment]
The output looks different because I'm adding descriptions to each data set, like this:

```php
class dataProvidersTest extends \PHPUnit_Framework_TestCase
{
    public function provideData()
    {
        return [
            'triple a' => ["aaa"],
            'triple b' => ["bbb"],
            'triple c' => ["ccc"],
        ];
    }

    /**
     * @dataProvider provideData
     */
    public function testMe($a)
    {
    }
}
```

The output without the fix:

```
Unit Tests (1) ------------------------------
UnitTests\dataProvidersTest::testMe |  Ok
UnitTests\dataProvidersTest::testMe |  Ok
UnitTests\dataProvidersTest::testMe |  Ok
---------------------------------------------

```

The output with the fix:

```
Unit Tests (1) -------------------------------------------------------------------------
UnitTests\dataProvidersTest::testMe | "triple a"                                  Ok
UnitTests\dataProvidersTest::testMe | "triple b"                                  Ok
UnitTests\dataProvidersTest::testMe | "triple c"                                  Ok
----------------------------------------------------------------------------------------
```

**Pull request merged**
