### PR TITLE
Filter HTML report.

### PR DESCRIPTION
**Pull request by raistlin**
Added a 'toolbar' for easy filtering.
Click on every statusCode toogle visibility of given status.
Additionally there is a "Show all" button.

This time against 2.0

### CODE REVIEW

**Comment by raistlin** [comment]
Some improvements of #1669

**Comment by DavertMik** [comment]
Thanks!

**Comment by DavertMik** [comment]
ups

**Comment by DavertMik** [comment]
@raistlin looks like markup should be fixed a bit

**Comment by raistlin** [comment]
I'm not a a good UI designer, CSS is black magic to me, but will try to fix it.

**Pull request merged**
