### PR TITLE
Added new option --disable-coverage-php to skip coverage.serialized report

### LINKED ISSUE #6760: Allow to disable coverage.serialized report and reduce memory usage.
#### What are you trying to achieve?
Currently `SebastianBergmann\CodeCoverage\Report\PHP` runs by default
Saving this  report consumes a lot of memory for the large projects. 
I want to be able to disable generating this type of coverage report.

#### What do you get instead?

My propose to add some new option `--disable-coverage-php` this will not provoke BC changes
```bash
php bin/codecept run unit --coverage --coverage-html --disable-coverage-php
```

Or changing behaviur of the CLI. If we was't call `--coverage` option but call any other `--coverage-*` format than don't generate default php serialize  report.
```bash
php bin/codecept run unit --coverage-html
```

### PR DESCRIPTION
**Pull request by adrenalinkin**
closes #6760 

Add some new option `--disable-coverage-php` this will not provoke BC changes
```bash
php bin/codecept run unit --coverage --coverage-html --disable-coverage-php
```

### CODE REVIEW

**Comment by SamMousa** [comment]
LGTM.

**Comment by adrenalinkin** [comment]
@SamMousa Hello! Did you read issue #6760?
I don't want to break compatibility in CLI. let's see examples:

### AS IS
`php bin/codecept run unit --coverage-html` will generate PHP report + HTML Report
`php bin/codecept run unit --coverage` will generate PHP report

### Version with `--coverage-php`
`php bin/codecept run unit --coverage-html` will generate only HTML Report **BC changes**
`php bin/codecept run unit --coverage` will generate **IDK What - need suggestions**
`php bin/codecept run unit --coverage-php` will generate only PHP Report

### Version with `--disable-coverage-php`
`php bin/codecept run unit --coverage-html` will generate PHP report + HTML Report **No BC**
`php bin/codecept run unit --coverage` will generate only PHP Report **No BC**
`php bin/codecept run unit --coverage-html --disable-coverage-php` will generate only HTML Report

**Comment by SamMousa** [comment]
I did read it. Makes sense. Can you recreate the PR targeted at the `main` branch?

**Comment by adrenalinkin** [comment]
@SamMousa Done

**Review by SamMousa — APPROVED** [review]

**Comment by adrenalinkin** [comment]
@SamMousa Pls don't forget merge documentation update
https://github.com/Codeception/codeception.github.com/pull/864

**Pull request merged**
