### PR TITLE
Dependency injection support

### PR DESCRIPTION
**Pull request by splinter89**
Resending #1164

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks! Finally I merged this and it is now in master branch
Waiting to get this working for 2.1!

**Comment by splinter89** [comment]
Here you go

**Comment by DavertMik** [comment]
@splinter89 thanks, I already merged this manually. Probably I will need to discuss some points. Are you in Skype these days?

**Comment by splinter89** [comment]
> I already merged this manually

I don't see it.
Why don't you use this PR?

Yes, I'm in Skype every day at work, usually 10am-6pm.

**Comment by DavertMik** [comment]
@splinter89
> I don't see it.
> Why don't you use this PR?

Actually I did use this PR. This is how GitHub works, if PR can't be merged automatically it provides instructions to do that manually. Which actually I did. However it didn't track, that I did it. 

I'm in the middle of refactoring, I will push my changes to master later today. 

> Yes, I'm in Skype every day at work, usually 10am-6pm.
Am I using the wrong Skype or you are not replying? Ping me pls: davert.ua

**Comment by splinter89** [comment]
I rebased this branch on master so you can merge it automatically now.

**Comment by DavertMik** [comment]
Thank you, this branch is already merged. Di works really really smoothly on master and I feel really good of new features it brings! Thanks for good work!

**Pull request closed without merging**
