### PR TITLE
bugfix: Symfony tests always fail when the profiler is disabled

### PR DESCRIPTION
**Pull request by dizzy7**

### CODE REVIEW

**Comment by DavertMik** [comment]
@raistlin is everything ok here?

**Comment by dizzy7** [comment]
Code using this method (debugResponse, seeEmailIsSent) takes into account the possibility of lack of service profiler.
In my case (258 gherkin tests) everything works properly. Besides, disabling profile service in symfony config reduce memory consumption and speedup tests (7.02 minutes, 198MB -> 5.79 minutes, 158.00MB)

**Comment by raistlin** [comment]
Seems ok.

**Comment by DavertMik** [comment]
Thanks

**Pull request merged**
