### PR TITLE
Add annotation `@skipDbCleanup`

### PR DESCRIPTION
**Pull request by josephzidell**
Add optional annotation `@skipDbCleanup` on a test method to hand-pick certain tests that don't care about DB cleanup. This allows most tests to use cleanup. This would allow a per-test override of config `cleanup: true`

Implements #5012

### CODE REVIEW

**Comment by johannesschobel** [comment]
Can you add tests to show that it actually works?!

**Comment by josephzidell** [comment]
I could try. Never written tests for codeception before

**Comment by johannesschobel** [comment]
Then now is the time I guess.. :D the is a "how to" in the wiki!

**Comment by DavertMik** [comment]
Very good initiative. The only concern here is how to make it documented. 
Also the same effect can be achieved via https://codeception.com/docs/06-ModulesAndHelpers#Runtime-Configuration-of-a-Test

(so yeah, documentation is a thing. If it's hard to find you will never know how to implement things)

**Comment by josephzidell** [comment]
@DavertMik Your approach is much better and more generic, and will solve many more use-cases
@sevastyanovio thanks for implementation.

Let me know whether I can be of assistance here.

**Comment by josephzidell** [comment]
Can annotations be placed at the class level? I think both class- and method- level would be useful.

**Comment by josephzidell** [comment]
@sevastyanovio Were you able to take a crack at an implementation?

**Comment by Naktibalda** [comment]
This PR died from the old age after the target branch was deleted.
If you want to try again, please make a new pull request to 4.0 branch (or newer if things moved on again,  changes affecting Db module must be made to https://github.com/Codeception/module-db

**Pull request closed without merging**
