### PR TITLE
Update install, split, run and merge

### PR DESCRIPTION
**Pull request by eXorus**
First  step to have to fix issue #3261 

And fix for robo-paracept is here https://github.com/Codeception/robo-paracept/pull/9

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks!

**Comment by eXorus** [comment]
@DavertMik It seems that all my doc changes about parallelExecution are not online

http://codeception.com/docs/12-ParallelExecution

Do you know why ?

**Comment by Naktibalda** [comment]
The docs will be updated when 2.2.3 is released

**Comment by eXorus** [comment]
ok thanks

**Pull request merged**
