### PR TITLE
Added ZF tests to Travis

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks. But it looks like Zend Framework is not found

**Comment by Naktibalda** [comment]
I added require_once __DIR__.'/../vendor/autoload.php';
to https://github.com/Naktibalda/codeception-zf1-tests/blob/master/tests/_bootstrap.php

**Comment by Naktibalda** [comment]
My ZF1 tests passed, I will add ZF2 tests now.

OK (13 tests, 19 assertions)

The command "php codecept run functional -c frameworks-zf1" exited with 0.

**Comment by DavertMik** [comment]
:+1:

**Comment by Naktibalda** [comment]
It is good now.

FAILURES!                              

Tests: 13, Assertions: 19, Failures: 1.

The command "php codecept run functional -c frameworks-zf2" exited with 1.

One test failed because I forgot to merge one commit to the master branch of zf2 site,
the next build will pass.

Is this pull request alright? I can create a clean one with 1 or 2 commits if this one is too dirty.

**Comment by DavertMik** [comment]
Thanks, PR looks good to me. I will rerun Travis build to see the failing test is passing now

**Comment by DavertMik** [comment]
Sorry but ZF2 tests on Travis still fail :(

**Comment by Naktibalda** [comment]
It passed now :)

**Comment by DavertMik** [comment]
Great!

**Comment by DavertMik** [comment]
Thank you, that was an invaluable contribution!

**Pull request merged**
