### PR TITLE
HTML report to include screenshots of failures from WebDriver

### PR DESCRIPTION
**Pull request by DavertMik**
* added `reports` section to MetaData in tests
* WebDriver to store html and png reports to metadata
* improved styling of HTML report

selection_154

### CODE REVIEW

**Comment by Naktibalda** [comment]
How are you going to support multiple screenshots per test? #3594

**Comment by DavertMik** [comment]
> How are you going to support multiple screenshots per test? #3594

I won't. For multiple screenshots we have Recoder and API to build any custom extension to handle that.

**Comment by DavertMik** [comment]
Added HTML reports to InnerBrowser

selection_156

**Comment by rebas82** [comment]
1) when i run test by selenium server (chrome), screenshot is only from visible screen. When i run test by phantomjs, screenshot is frome complete page (i can see everything on page).

Is it posible have complete screenshot from selenium server as is from phantomjs?

2) some people dont like screenshots in html report, or have own function for doing fail screenshot (as me). Is it posible doing some settings to YML file, where tester set if they need failscreenshot or not need?

**Comment by Naktibalda** [comment]
@rebas82 You should raise a separate ticket for these suggestions.

**Comment by rebas82** [comment]
ok

**Comment by Sereda-Fazen** [comment]
Hi everybody!
I've updated Codeception to 2.2.6. and when I run tests. I received in HTML Report the following
image

We together with my collegue added the feature in order to work in HTML Report.
1. In the file ResultReport/HTML.php we added the string

> $png = "<tr><td class='error'><div class='screenshot'>failure screenshot</div></td></tr>";

Currently it works but the path in the HTML Report is absolute

**Comment by hadouke** [comment]
Is ther3 any updates on this? I also have trouble with showing screens in new report

**Pull request merged**
