### PR TITLE
Codeception 5.0

### PR DESCRIPTION
**Pull request by Naktibalda**
- [x] Merge [the latest branch](https://github.com/Codeception/phpunit-wrapper/tree/10.0) of phpunit-wrapper back to Codeception/Codeception
- [x] Merge "Improved compatibility with PHPUnit 7+" changes made in [codeception/codeception](https://github.com/Codeception/Codeception/pull/5894) and [phpunit-wrapper](https://github.com/Codeception/phpunit-wrapper/pull/77) repos.
- [x] Remove some old PHPUnit compatibility hacks
- [x] Remove support for Symfony 3 (raise the lowest supported version to 4.4)
- [x] Remove support for old versions of php-dotenv 2 and 3 (possibly 4 too).
- [x] Remove support for codeception/stub v2
- [x] Upgrade to the latest major versions of the following dependencies:
  - [x] ~~codeception/specify 0.* to 1.*~~ Removed dependency instead because it wasn't used by tests
  - [x] ~~monolog/monolog 1.* to 2.* (used by ext/Logger.php)~~ Removed dependency instead because Logger has no tests.
  - [x] ~~squizlabs/php_codesniffer 2.* to 3.*~~ Removed because it wasn't part of CI and code style wasn't enforced. It can be readded latter.
- [x] Delete deprecated code
  - [x]  [Codeception\Util\Stub](https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Util/Stub.php) was deprecated in 2.3.8, 3 years ago
  - [x] [settings: bootstrap:](https://github.com/Codeception/Codeception/commit/55e91e14567c7476bc29e778eda976d336c24f58) setting was deprecated in 3.1.0 in August 2019
- [x] Review all phpunit-wrapper code in src/PHPUnit/.
- [x] Run tests of require-dev modules in Github Actions (this change will be backported to 4.1)
- [ ] Make [codeception/stub](https://github.com/Codeception/stub) compatible with PHPUnit 10.
- [ ] Update files in src/PHPUnit/NonFinal directory with the latest revision of their counterparts in PHPUnit (the only difference was that they have no `final` keyword, because some Codeception classes extend them).
- [ ] Make it work with PHPUnit 10 after final release.
- [ ] Check how much work it is to make with PHPUnit 9. Support it if it is simple (e.g. a few version or method_exists conditions).
- [ ] Repeat this process with PHPUnit 8.

There are so many commits in this pull request because I merged entire commit history of phpunit wrapper using `git merge --allow-unrelated-histories` 
Source: https://www.w3docs.com/snippets/git/how-to-merge-two-git-repositories.html

### CODE REVIEW

**Comment by Naktibalda** [comment]
phpunit-wrapper runs module-asserts tests because PHPUnit removes or changes some assertions in breaking way in every major release.
I added running tests of other modules because they are already there, so it is a small change, and I hope that they will prevent us from breaking some module related functionality.
They can be removed later if build process takes too long.

**Comment by Naktibalda** [comment]
I think that this branch can be merged now to allow other people to contribute to 5.0.
PHPUnit 10 is a moving target and PHPUnit10 support won't be complete until 10.0.0 is released on 5th of February.
I will open another pull request for PHPUnit 10.

**Comment by DavertMik** [comment]
> I think that this branch can be merged now to allow other people to contribute to 5.0.

Absolutely agree!
Going to clone it now

**Comment by ThomasLandauer** [comment]
One more TODO: Remove Cept format completely, see https://github.com/Codeception/Codeception/pull/6144#issuecomment-800559695

**Pull request merged**
