### PR TITLE
merged params in rest module

### PR DESCRIPTION
**Pull request by albertleao**
#3957

### CODE REVIEW

**Comment by Naktibalda** [comment]
@albertleao Please merge changes from 2.2 branch (or rebase) to get the tests pass.

**Comment by albertleao** [comment]
Great point. I will attempt another pull with a `setDefaultParameters`

**Comment by Naktibalda** [comment]
Do you really need a function for that?
The same result could be achieved this way:
```php
$defaultParams = ['token' => '1234567'];
$I->sendPOST('/', ['foo' => 1] + $defaultParams);
$I->sendPOST('/', ['bar' => 2] + $defaultParams);
```

**Comment by albertleao** [comment]
Yes I realize the same functionality can be achieved the way you described. But instead of having to to have  
` $defaultParams = ['token' => '1234567']; `
and the + for every test, I could set it up in my actor so that it can be defaulted for any type of test suite.

**Pull request closed without merging**
