### PR TITLE
Update shim.php

### PR DESCRIPTION
**Pull request by josephzidell**
Fix indentation [skip ci]

### CODE REVIEW

**Comment by ddinchev** [comment]
Imho if we are going to modify indentations, these should be imposed and checked by some coding standards tool like CodeSniffer.

**Comment by josephzidell** [comment]
I agree

**Comment by DavertMik** [comment]
Yeah, shim.php outstands from our main code base so we don't have any strict policy about it's code. 
But thanks for improving it.

**Comment by josephzidell** [comment]
Thanks @DavertMik

**Pull request merged**
