### PR TITLE
Fix compatibility with PHPUnit error expectations

### PR DESCRIPTION
**Pull request by Naktibalda**
Replaces #6461

### CODE REVIEW

**Comment by calvinalkan** [comment]
@Naktibalda Can we release a 4.2 version once this is merged? Together with the other PRs merged lately.

**Comment by Naktibalda** [comment]
that's the plan.

**Comment by Naktibalda** [comment]
@calvinalkan Most likely this functionality won't work with PHPUnit 10, unless we implement error expectations in [Codeception\Test\Unit](https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Test/Unit.php) but in that case it will be limited to tests extending `Codeception\Test\Unit`.

See https://github.com/sebastianbergmann/phpunit/commit/d4b3d9d89fa82ae38712ad96b64b1cd4500eb991

**Comment by Naktibalda** [comment]
We can't override `expectNotice` and other methods in Unit class, because they are declared as final in TestCase.
If this functionality is important, we will have to use different method names.

Emitting PHPUnit event is not an option too, because it fixes `expect` functionality, but unexpected errors won't be reported by Codeception.

**Comment by calvinalkan** [comment]
> @calvinalkan Most likely this functionality won't work with PHPUnit 10, unless we implement error expectations in [Codeception\Test\Unit](https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Test/Unit.php) but in that case it will be limited to tests extending `Codeception\Test\Unit`.
> 
> See [sebastianbergmann/phpunit@d4b3d9d](https://github.com/sebastianbergmann/phpunit/commit/d4b3d9d89fa82ae38712ad96b64b1cd4500eb991)

Are there other usecase other than in classes extening `Unit`?

Of the top of my head I cant think of any.

In Browser and cli tests you cant make assertions about errors this way no matter what

**Comment by Naktibalda** [comment]
Tests extending \PHPUnit\Framework\TestCase directly.

**Pull request merged**
