### PR TITLE
Add `packages` option for application packages.

### PR DESCRIPTION
**Pull request by jonathantorres**
Issue: https://github.com/Codeception/Codeception/issues/1783

### CODE REVIEW

**Comment by janhenkgerritsen** [comment]
I do not develop packages for Laravel 5, so could you please explain to me what the issue is that this change solves?

**Comment by jonathantorres** [comment]
Exactly as https://github.com/Codeception/Codeception/issues/1208  (you can still use the workbench on Laravel5 as a separate package)

When you run your main app tests you'll also want to run the tests on the packages. But since each package must have it's own `codeception.yml` file when the package tests are run, codeception tries to run the tests from it's own `codeception.yml` file and not from the main laravel app.

So I added another option to the module in which you can specify the directory in which you'll store your packages. (Since in laravel5 it can be any name, not necessary "workbench")

**Comment by DavertMik** [comment]
@janhenkgerritsen looks good to me. Should I merge?

**Comment by janhenkgerritsen** [comment]
Also looks good to me, so you can merge this.

**Comment by DavertMik** [comment]
done. thank you!

**Pull request merged**
