### PR TITLE
add click by button title

### PR DESCRIPTION
**Pull request by gimler**
Make it possible to click on a button by title. For example when you have a form button with only a font icon
```
<button type="submit" class="btn btn-default" title="save">
  <i class="fa fa-save"></i>
</button>
```

### CODE REVIEW

**Comment by DavertMik** [comment]
Hey, good idea. 
Is the title a valid attribute for `button`?

**Comment by gimler** [comment]
@DavertMik yes, see https://www.w3schools.com/tags/tag_button.asp -> "Global Attributes" -> https://www.w3schools.com/tags/ref_standardattributes.asp

**Comment by DavertMik** [comment]
Thanks, however some tests are failing. I will restart the build on CI but maybe you will need to look at it.
Please try to fix 

tests/web/WebDriverTest.php:testClickHashLink
tests/web/WebDriverTest.php:testClickHashButton

**Comment by gimler** [comment]
@DavertMik tests fixed

**Comment by DavertMik** [comment]
Thank you! Good job! :+1:

**Pull request merged**
