### PR TITLE
[Doctrine2] expose refresh and clear [obsoleted by #5628]

### LINKED ISSUE #4526: Suggestion for Doctrine2 Module: refresh()
It looks like, if an entity gets modified by the app, there's no cool way to refresh it in Codeception.

Sample pseudo code:
```php
$user = $I->grabEntityFromRepository(...);
$I->assertTrue($user->isActive());
$I->submitForm(...); // some form which changes the user to inactive
// This fails, since `$user` is still the same as above:
$I->assertFalse($user->isActive());
```

Right now, I can't think of any other way than to reload the entity from the database, which means repeating the first line:
```php
// ... 
$modifiedUser = $I->grabEntityFromRepository(...); // same as in line 1 above
$I->assertFalse($modifiedUser ->isActive());
```

But something like this would be nicer:
```php
// ... 
$I->refreshEntity($user); // would be cool :-)
$I->assertFalse($user ->isActive());
```

### Details

* Codeception version: 2.3.5
* PHP Version: 7.1

### PR DESCRIPTION
**Pull request by alexkunin**
Closes #4526.

### CODE REVIEW

**Comment by alexkunin** [comment]
Oops, accidentally rebased onto other PR which is not yet accepted. I guess not a big deal if that other PR will be merged.

**Comment by alexkunin** [comment]
OK, rebased, let's see if tests are still green...

**Comment by Naktibalda** [comment]
It looks worse now (18 commits), I squashed commits of PR that I merged, because it consisted of 8.
It may be necessary to cherry-pick this change to a new branch.

**Comment by alexkunin** [comment]
Thanks for the hint, I have my changes cherry-picked into new branch and created new PR: #5628.

**Pull request closed without merging**
