### PR TITLE
Add a note about how to contribute documentation

### PR DESCRIPTION
**Pull request by javigomez**
I got the idea from https://github.com/Codeception/codeception.github.com/issues/17#issuecomment-104038409

### CODE REVIEW

**Comment by javigomez** [comment]
If you agree with it I can send it too to the master branch

**Comment by DavertMik** [comment]
:+1:

**Comment by Ragazzo** [comment]
@DavertMik why it is not included in main `README.md` in section `Contributing` ?

**Comment by javigomez** [comment]
good point @Ragazzo. I have created #1969 with your suggestion.

**Pull request merged**
