### PR TITLE
Removed generated files from git

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by Naktibalda** [comment]
For some odd reason one actor is not regenerated in the sandbox.

**Comment by DavertMik** [comment]
Ok, let me check this

**Comment by DavertMik** [comment]
I have a fix for that. 
Probably Action classes are not rebuilt because sandbox is never execute for all suites but per specific tests only... Or maybe this happens because we are copying folders for each run. Anyway

**Comment by DavertMik** [comment]
I created another PR with the fix.

I think we should use organization repos for PRs so it would be easier to improve our patches.

**Pull request closed without merging**
