### PR TITLE
Get the id of a Facebook test user

### PR DESCRIPTION
**Pull request by ipalaus**
Add a new method to obtain the user id.

### CODE REVIEW

**Comment by ipalaus** [comment]
PS: The failing tests are not related to my changes. Just checked and validated it's working.

**Comment by Revisor** [comment]
It looks like you reformatted src/Codeception/Module/Facebook.php, since the diff tool is completely confused. Maybe line breaks?

**Comment by DavertMik** [comment]
Yeah, it's hard to understand changes because of reformatting (

**Comment by Revisor** [comment]
Davert, you can prevent line break reformatting globally by using the .gitattributes file.
https://help.github.com/articles/dealing-with-line-endings/

An example
```
# Auto detect text files and perform LF normalization
*       text=auto

# Denote text files explicitly, normalize line endings to LF on checkin and forbid conversion to CRLF on checkout
# Without eol=lf, core.autocrlf might come in effect
*.html  eol=lf diff=html
*.css   eol=lf
*.js    eol=lf
*.sql   eol=lf
*.php   eol=lf diff=php
*.yml   eol=lf
*.xml   eol=lf
*.dist  eol=lf
*.conf  eol=lf
*.json  eol=lf
*.lock  eol=lf

# Denote all files that are truly binary and should not be modified.
# Git would detect them automatically, but this will save the autodetection
*.png   binary
*.jpg   binary
*.gif   binary
*.ico   binary
*.zip   binary
*.jar   binary
*.docx  binary
*.docx  binary
*.dot   binary
*.xls   binary
*.otf   binary
*.eot   binary
*.ttf   binary
*.ttf   binary
*.woff  binary
*.phar  binary
```

**Comment by DavertMik** [comment]
Thanks. Getting this merged!

@Revisor I will add .gitattributes as you suggested

**Comment by DavertMik** [comment]
@ipalaus by the way, this module needs a new maintainer. Could you be the one? ;)
Currently I disabled Facebook tests as they are permanently failing. I don't use Facebook API so I don't have a clue what might go wrong there. Maybe you can help to figure out what is happening and have to get it fixed?

**Pull request merged**
