### PR TITLE
Respect absolute paths in Yii2 module

### PR DESCRIPTION
**Pull request by SilverFire**

### CODE REVIEW

**Comment by Naktibalda** [comment]
I wonder if this is a bugfix or a breaking change. It could be the latter.

@Slamdunk what do you think about this change?

**Comment by SilverFire** [comment]
It's partially a breaking change because it will (obviously) break paths that start with a `/`, but it was never advised to use absolute paths as relative.

**Comment by samdark** [comment]
Yes. That sounds fine to me.

**Comment by DavertMik** [comment]
This also won't work for Windows absolute paths...

**Comment by SilverFire** [comment]
> This also won't work for Windows absolute paths...

Good point. Maybe we should introduce a function on top of `codecept_root_dir()` that will check whether the path is absolute?

```php
function codecept_resolve_path($path) {
    return $path[0] === DIRECTORY_SEPARATOR ? $path : codecept_root_dir($path);
}
```

**Comment by DavertMik** [comment]
@SilverFire good idea

**Comment by SilverFire** [comment]
Added function and changelog. Ready for review.

**Comment by DavertMik** [comment]
Looks good!

**Comment by bscheshirwork** [comment]
```php
function codecept_resolve_path($path) {
    return $path[0] === DIRECTORY_SEPARATOR ? $path : codecept_root_dir($path);
}
```
This function return a different result in cases (in yii2-app-advanced for example)
* global `codeception.yml` within includes (
```yml
include:
    - common
    - frontend
    - backend
```
)
* from frontend/backend/common folder directly

for relative path. And this function proposed a way to avoid it. I am right?

**Comment by SilverFire** [comment]
Yes, If I have correctly understood your question.

**Pull request merged**
