### PR TITLE
[WIP] Clean up

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed all white spaces and extra lines from our documentation :smile:

### CODE REVIEW

**Comment by Naktibalda** [comment]
Thanks, but all the files in docs/modules and docs/reference are auto-generated from .php files,
so your changes will be lost.
It would be better to fix the generator - please take a look at buildDocs method in Robofile.php

**Comment by carusogabriel** [comment]
@Naktibalda Oh, okay. I’m gonna search how we can fix it, and amend this PR 👨‍💻

Thanks for guide me!

**Comment by carusogabriel** [comment]
@Naktibalda Can you please tell me how do you run the `RoboFile` class to generate the docs? I guess I fixed the issues, but I couldn't find how to run it :innocent:

**Comment by Naktibalda** [comment]
Download http://robo.li/robo.phar and run it in Codeception directory.

**Comment by DavertMik** [comment]
Thanks! That looked like a minor issue the days when I created that build:docs script. But I didn't know how to handle it. After few years you finally improved that part. Thank you! If you have other ideas how to make docs better - I'm listening. 

P.S. I hope that won't break anything on website :)

**Pull request merged**
