### PR TITLE
Prevent publishing of assets and `@webroot` directory creation.

### PR DESCRIPTION
**Pull request by dmitry-kulikov**
Fix for #3706.

### CODE REVIEW

**Comment by DavertMik** [comment]
Please resend this to 2.2 branch. Master stands for next major release

**Comment by githubjeka** [comment]
Do you use the function `mockAssetManager()` in Acceptance Testing ?

**Comment by dmitry-kulikov** [comment]
I will reopen pull request.

> Do you use the function mockAssetManager() in Acceptance Testing ?

I'm using config similar to this https://github.com/yiisoft/yii2-app-basic/blob/master/tests/acceptance.suite.yml.example, with such config method
\Codeception\Lib\Connector\Yii2::mockAssetManager is executed in acceptance testing, but real asset manager will be used, not mock. It is ok for me. If you want to mock asset manager during acceptance testing - I do not know how to do it.

**Comment by githubjeka** [comment]
I was worried that the mockAssetManager will be used for acceptance tests. PR is OK.

**Pull request closed without merging**
