### PR TITLE
Sync changes

### PR DESCRIPTION
**Pull request by janhenkgerritsen**
Sync changes from my own repository of the Laravel 5 module. 

There is no need to release a new version, these changes can just go out when you plan a new release yourself.

### CODE REVIEW

**Comment by DavertMik** [comment]
@janhenkgerritsen thanks!

I was trying to contact you via Facebook. Maybe that was not a good option, but can we talk somehow. I'd like to propose you to join Codeception team and get all means to maintain Laravel modules. We can talk in FB or in skype: `davert.ua`

**Comment by DavertMik** [comment]
btw, i see only whitespace fixes in commit 0.o

**Comment by janhenkgerritsen** [comment]
Yeah that's why I said you don't have to release a new version. But these changes got lost when I moved some code around between two repositories, so I decided to submit the PR already, so I do not forget them at a later point in time :-)

I just checked Facebook and now I see your message from last Friday. I did not reply because I had not seen it yet, somehow I have not received a notification. But we can continue our conversation there.

**Comment by DavertMik** [comment]
FYI team members are: @samdark, @zbateson , @tiger-seo , and @DavertMik

**Pull request merged**
