### PR TITLE
Removing Cept

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by DavertMik** [comment]
thanks, it is a good idea to start removing it from mentioning anywhere
but probably for now, we should just keep this format inside the codebase for BC and to keep our internal tests running as well.

**Comment by ThomasLandauer** [comment]
OK, so please merge this now, to remove it from docs.
I added the Cept removal to the v5 TODO list: https://github.com/Codeception/Codeception/pull/6067#issuecomment-800576390

**Comment by gimler** [comment]
@ThomasLandauer why was the cept format removed?

**Comment by ThomasLandauer** [comment]
@gimler See https://github.com/Codeception/Codeception/pull/4259 for the beginning of the story :-)

If you're asking why Cept is eventually going to be dropped from Codeception altogether, I can only tell you my personal opinion: In short: Cest is PHP, and Gherkin is (somewhat) natural language. Cept is something in between. And, AFAIK, while Gherkin is some sort of standard today, Cept has always been Codeception-only.

**Pull request merged**
