### PR TITLE
support simple wildcard includes

### PR DESCRIPTION
**Pull request by nzod**
Issue #2016

Allow giving wildcards in codeception.yml include paths to avoid hand-listing them.

### CODE REVIEW

**Comment by nzod** [comment]
Redone on 2.1.

Tests coming soon!

**Comment by DavertMik** [comment]
Good! Thanks. Waiting for tests to merge it

**Comment by nzod** [comment]
I went by what the documentation recommends, to create a CLI test. Is this OK?

**Comment by DavertMik** [comment]
Thanks. This is pretty awesome feature!

**Pull request merged**
