### PR TITLE
Deleted example for *public* dataprovider function

### PR DESCRIPTION
**Pull request by ThomasLandauer**
See https://github.com/Codeception/Codeception/pull/4225#issuecomment-302549188

BTW: Is http://codeception.com/docs/07-AdvancedUsage not updated in real-time from `07-AdvancedUsage.md`? I still see the old version there...

### CODE REVIEW

**Comment by Naktibalda** [comment]
but why?

**Comment by ThomasLandauer** [comment]
Why delete it? => Because it's useless! Giving a detailed example for a useless scenario only confuses readers (since they think it must be important)

**Comment by DavertMik** [comment]
Yes, better to delete it as it adds nothing more than the basic example.

**Comment by ThomasLandauer** [comment]
Well, OK, then please merge this :-)

**Pull request merged**
