### PR TITLE
[WIP] Implement Event class

### LINKED ISSUE #5927: Remove class_alias Symfony\Component\EventDispatcher\Event
By [adding](https://github.com/Codeception/Codeception/blob/4.1/shim.php#L41) a class alias in the Symfony space, you violating work in other packages that use this class to check the version.

Example:
[enqueue/async-event-dispatcher](https://github.com/php-enqueue/async-event-dispatcher/blob/master/AsyncEventDispatcher.php#L7)

### PR DESCRIPTION
**Pull request by qRoC**
This PR resolves #5927

### CODE REVIEW

**Comment by Naktibalda** [comment]
Travis tests on PHP 7.2, 7.3 and 7.4 failed, which means that your change is incompatible with Symfony 5.
If you can make it work, I will merge it.

**Comment by qRoC** [comment]
@Naktibalda
We can change signature in Codeception\PHPUnit\DispatcherWrapper to:
```php
     use Symfony\Component\EventDispatcher\Event as ComponentEvent;
     use Symfony\Contracts\EventDispatcher\Event as ContractEvent;
    ...
     * @param ContractEvent|ComponentEvent $eventObject
     */
    protected function dispatch(EventDispatcher $dispatcher, $eventType, $eventObject)
```

And set minimal version to:
```
"codeception/phpunit-wrapper": ">6.0.15 <6.1.0 | ^6.8.2 | ^7.8.1 | ^8.1.3 | ^9.0.3",
```
Its ok?

**Comment by Naktibalda** [comment]
Almost, the next release of 6.0 branch of phpunit-wrapper will be 6.0.20.

Also, since you are removing class alias, please make DispatchWrapper use `class_exists(Event::class)` condition because current condition has it's own issues with Symfony 4.4 https://github.com/symfony/symfony/pull/35892

**Comment by Naktibalda** [comment]
@qRoC  What's the status of this change?

**Comment by qRoC** [comment]
@Naktibalda I am finishing my tasks this week and getting started this

**Comment by W0rma** [comment]
@qRoC Are you still working on this PR?

**Comment by W0rma** [comment]
@Naktibalda Should this PR be closed since #5927 has been closed, too? The alias will be removed in Codeception 5.0

**Comment by Naktibalda** [comment]
Thanks, I'm closing it now.

**Pull request closed without merging**
