### PR TITLE
Fix PHP 8.4 deprecation.

### PR DESCRIPTION
**Pull request by kagg-design**

### CODE REVIEW

**Review by ThomasLandauer — APPROVED** [review]

**Review by W0rma — APPROVED** [review]

**Comment by W0rma** [comment]
This PR should fix the last remaining PHP 8.4 deprecation warning.

@SamMousa @Naktibalda It would be great to have a new release after this MR is merged.

**Review by SamMousa — APPROVED** [review]

**Review by TavoNiievez — APPROVED** [review]

**Comment by ThomasLandauer** [comment]
Could you please tag a new version, to actually get rid of those warnings?

**Comment by ThomasLandauer** [comment]
Ping @Naktibalda :-)

**Comment by laoneo** [comment]
Probably not more like what he did in https://github.com/Codeception/Codeception/commit/3b2d7d1a88e7e1d9dc0acb6d3c8f0acda0a37374. And then a tag so the release will appear on packagist. The releases itself do not look like that were some special assets built.

**Pull request merged**
