### PR TITLE
Environment subfolders support

### PR DESCRIPTION
**Pull request by Zifius**
Sorry, first take was a blindly patch. This is actually tested

### CODE REVIEW

**Comment by DavertMik** [comment]
Can you provide a small background. What was the issue?

**Comment by Zifius** [comment]
Hi @DavertMik, sure - I implemented the feature initially in #2381, but by testing today the head of 2.1 branch I discovered that changing search depth didn't really work as the subfolder wasn't accounted for config loading so actually environments in subfolders werenn't loaded at all so this PR fixes that. Not sure if totally ok code wise so let me know if you have any notes. Thanks

**Comment by DavertMik** [comment]
why not just increase the search depth?

```
            ->depth('< 2');
```

**Comment by Zifius** [comment]
@DavertMik that's what I did in the initial PR but $path here https://github.com/Zifius/Codeception/commit/72e50e14982699e6aea53012f902c7d6446eeaae#diff-a14abaeb14e2165d64e4de51c4168d5bL309 is the absolute path to _envs folder, it doesn't include subfolders thus no subfolders are used when merging the configs

**Comment by Zifius** [comment]
But I agree that it's complicated, perhaps just need to collect envs with subfolder path in this loop https://github.com/Zifius/Codeception/commit/72e50e14982699e6aea53012f902c7d6446eeaae#diff-a14abaeb14e2165d64e4de51c4168d5bR300. Perhaps that regex is also overkill. I'll look into it and rework

**Comment by Zifius** [comment]
Hi @DavertMik, please review the latest updates for this PR. Thank you

**Comment by DavertMik** [comment]
Yeah, latest fix is much more better than previous one

**Comment by DavertMik** [comment]
I will write a failing test and merge it afterwards )

**Comment by Zifius** [comment]
Cool, thanks :+1:

**Comment by DavertMik** [comment]
Works as expected. Thank you!

**Comment by Zifius** [comment]
Cheers, happy to contribute!

**Pull request merged**
