### PR TITLE
fix haveFakeRepository in the doctrine module

### PR DESCRIPTION
**Pull request by laszlo-karpati**
Fix https://github.com/Codeception/Codeception/issues/4211

### CODE REVIEW

**Comment by DavertMik** [comment]
Probably this has been working in earlier versions of Doctrine
Could you check when they did change their internal API?

**Comment by laszlo-karpati** [comment]
@DavertMik I wrote about it in the connected issue as well:

they changed this part of their internal API with this commit:
https://github.com/doctrine/doctrine2/commit/7eb744126ba5081ea51441a893dd950046777383

**Comment by DavertMik** [comment]
Could you leave the current implementation so for not to break things for users of old Doctrine?

**Comment by laszlo-karpati** [comment]
@DavertMik Sure,
I've just pushed the backward compatibility.

**Comment by DavertMik** [comment]
Thanks

**Comment by polki-bil** [comment]
Hello, we are still having problem. Symfony generates proxy class for EntityManager, so Doctrine2 module can't find repositories nor repositoriyFactory. 
class:
    `DoctrineORMEntityManager_00000000136fffc9000 ....`
and has only properties (shortened): 
```
    object(ReflectionProperty)[2677]
    public 'name' => string 'valueHolder593fb92bd0e38185253777' (length=33)
    object(ReflectionProperty)[3536]
    public 'name' => string 'initializer593fb92bd0e4f480946614' (length=33)
    object(ReflectionProperty)[3539]
    public 'name' => string 'publicProperties593fb92bd0dee937024105' (length=38)

```
We are using Symofny 3.3 and Doctrine 4.5
We tried various Symfony configs to prevent from generating this, but with no success. 
With this code added it works:
   ` $ReflectedEm->getParentClass()->hasProperty('repositoriyFactory');`

Thanks for any help

**Comment by laszlo-karpati** [comment]
Hi @polki-bil!

_I think you've mistyped your Doctrine's version, and you are using v2.5._

As I see Docrine was adding the entityManager's spl_object_hash to the repositoryList key's name in the DefaultRepositoryFactory since version 2.5.  

They added it with this commit, released in version 2.5:
https://github.com/doctrine/doctrine2/commit/a9847533e5d3c2efc15284fb93fb57a443978cf5

I'm using Doctrine v2.4 right now, but if I'll have time for it in the next days, I will try to figure out something for it.

Can you try it with the [v2.4's DefaultRepositoryFactory class](https://github.com/doctrine/doctrine2/blob/2.4/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php)?

**Pull request merged**
