### PR TITLE
Add compatibility with phpunit/php-timer:^4.0

### PR DESCRIPTION
**Pull request by W0rma**
Fixes https://github.com/Codeception/Codeception/issues/5932

### CODE REVIEW

**Comment by SamMousa** [comment]
Thanks!

**Comment by bou2you** [comment]
Thank for addressing this issue. My Codeception test run failed this morning because of this. 

When you do expect this fix to be available when I do a "composer update"? Will this fix be in a Codeception 4.1.6 update?

**Comment by mr-feek** [comment]
Thanks!

**Comment by Naktibalda** [comment]
I released 4.1.6

**Pull request merged**
