### PR TITLE
Bugfix groups by directory for Windows

### PR DESCRIPTION
**Pull request by tortuetorche**
Convert double backslash to single backslash.

See #2550 and https://github.com/Codeception/Codeception/pull/2551#issuecomment-167756694

### CODE REVIEW

**Comment by tortuetorche** [comment]
I don't why Semaphore build failed :pouting_cat:

**Comment by Naktibalda** [comment]
@tortuetorche don't worry about that.
Semaphore runs WebDriver tests only and WebDriver fails quite often.

**Comment by Naktibalda** [comment]
Since you are making this change, could you merge your line with the previous one and use this code instead?
```
$filename = str_replace(['\\\\', '//'], ['\\', '/'], $info['file']);
```

**Comment by tortuetorche** [comment]
Alright :smirk_cat:

**Comment by tortuetorche** [comment]
Done and the Semaphore's build is OK :smile_cat:

**Comment by tortuetorche** [comment]
@Naktibalda Many thanks for merging this :+1:

**Pull request merged**
