### PR TITLE
New REST / InnerBrowser Helper

### PR DESCRIPTION
**Pull request by johannesschobel**
Hi @DavertMik ,

This PR adds a new "helper" that allows loading custom `Stub`s from the `_data` directory of the current suite. This may be useful in the context of RESTful API testing (e.g., you can define the JSON documents to be sent to the API).

Further, you can define "placeholders" in the stub files and automatically replace them..

Consider the following example:
**STUB FILE:**
``` json 
{
  "data" : {
    "title" : "{{book-title}}",
    "author" : "{{book-author}}",
    "year" : "{{book-year}}"
  }
}
```

In the `REST` module you can call it like so:
``` php
$replacements = [
    'book-author' => 'JRR Tolkien',
    'book-title' => 'Lord of the Rings',
    'book-year' => 1954,
];

// $I is an Instance of an Tester that includes the REST module!
$stub = $I->loadAndPrepareStub('path/to/stub.json', $replacements);
```

The content of `$stub`, in turn, will then be:
``` json
{
  "data" : {
    "title" : "Lord of the Rings",
    "author" : "JRR Tolkien",
    "year" : "1954"
  }
}
```

I think, this will help to further improve API testing by separating.. Can you give me feedback on this?!
Will love to contribute again, if you agree :laughing: 

All the best

### CODE REVIEW

**Comment by DavertMik** [comment]
Sorry, it seems that this update adds an additional logic to InnerBrowser which goes beyond its scope. 
That's a breaking of single responsibility principle. How about making a new mudle for that purpose and publishing it as standalone package?

**Comment by johannesschobel** [comment]
Hey @DavertMik , thank you very much for your response on this..

I initially added it to the `InnerBrowser` as this module already had a `attachFile()` method..

I have 3 suggestions how to proceed. Which one do you prefer?!
1. Create a `FileLoaderTrait`, add the latter to the `InnerBrowser` and move the functionality to this Trait
2. Move the functionality to the `Filesystem` module
3. Create a dedicated `FileLoader` module and move it there.. 

What do you think would be best?
Cheers and thanks for you time and effort

**Comment by DavertMik** [comment]
I think the best option would be to create a standalone helper inside a custom package. 
Currently, I don't think this functionality belongs to any of core modules.

**Comment by johannesschobel** [comment]
Hey man, thanks again for your input on this..
Just to be sure, I got your point correct:

You would do something like this:
``` php
namespace Codeception\Module;

class FileLoader extends CodeceptionModule implements X, Y, Z {
// ...
}
```
right?

If you like, I can develop such a new module. What do you think?

Cheers

**Pull request closed without merging**
