### PR TITLE
Add SSH key support to the (S)FTP module

### PR DESCRIPTION
**Pull request by mattvot**
Adding support for sftp connections with an RSA SSH key.

### CODE REVIEW

**Comment by mattvot** [comment]
Hi, It looks like this enhancement was not included in 2.0.9 as planned. Is there anything I can do?

**Comment by mattvot** [comment]
Hi @DavertMik, It looks like this enhancement was not included in 2.0.9 as planned. Is there anything I can do?

**Comment by DavertMik** [comment]
Oh, sorry, looks like I missed that this PR was to master branch. 
Please resend this to 2.0 branch to see it in next stable release.
Sorry for delay. I was really busy these days :(

**Comment by mattvot** [comment]
Thanks. New PR https://github.com/Codeception/Codeception/pull/1659

**Pull request merged**
