### PR TITLE
Looking for group files can be really slow

### PR DESCRIPTION
**Pull request by pitpit**
This is caused by use of `Finder::path()` at https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/GroupManager.php#L43-L47 when `groups` parameter is set in codeception.yml

Finder is referencing every files in project root dir, then filters them according to string passed to `path()`. If a lot of files stand in project root dir, it can takes more than 2minutes to find a few group files.

Here's a patch to get rid of `Finder::path()`. It reduces elapsed time from several minutes to few seconds.

### CODE REVIEW

**Comment by pitpit** [comment]
testing fails on https://github.com/Codeception/Codeception/blob/2.2/tests/unit/Codeception/Module/PhpBrowserTest.php#L283 which is not related to this PR

----
Guzzle seems to not support request URL without starting slash anymore.
Could be fixed adding `$page = '/'.ltrim($page, '/');` at https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/InnerBrowser.php#L330

**Comment by Naktibalda** [comment]
#4028

**Comment by Naktibalda** [comment]
Please merge 2.2 branch to make the build pass.

**Comment by pitpit** [comment]
done

**Comment by laupiFrpar** [comment]
+1

**Comment by pitpit** [comment]
If you could have a look on this, please

**Comment by DavertMik** [comment]
Thank you for this performance improvement. Looks nice and elegant

**Pull request merged**
