### PR TITLE
Allow associative array names for buttons and input type submit

### PR DESCRIPTION
**Pull request by efrag**
Code and pull request following #2021

### CODE REVIEW

**Comment by zbateson** [comment]
Hi @efrag - 

Thanks for the pull request.  I'm a bit surprised by this one to be honest, your test works without your proposed changes to InnerBrowser (if you undo the three changes in InnerBrowser, run the tests, all is good).

Could this be an issue with Symfony, and not InnerBrowser/PhpBrowser?

**Comment by zbateson** [comment]
For clarification, actually field names with 'named' associative arrays (like foo[bar]) can be passed as strings or arrays.  The only exception to that is when you want sequenced array elements without passing the actual keys, because you can't have two elements named 'foo[]' passed in the array (only one could exist with that key in the array.)

So you could have:
```php
[
    'foo' => ['value1', 'value2'],    // sends 'foo[]'
    'bar[blah]' => 'value3',
    'bar[argh]' => 'value4',
    // or
    'baz' => [
        'key1' => 'value5',
        'key2' => 'value6',
    ]
]
```
and it would submit fine.

**Comment by efrag** [comment]
Hi @zbateson,

Thanks for looking into this and for your quick response. 

After your comment I re-run the tests on the Symfony2 app and noticed that I was using Codeception version 2.0.13 in which the test was failing. After upgrading to 2.0.14 the tests run successfully after adding a value on the submit and cancel buttons. 

So, again thank you for looking into this, shall we close this pull request?

**Comment by zbateson** [comment]
Aah, right - there was a fix somewhere related to this :) I always forget what's already been released.

**Pull request closed without merging**
