### PR TITLE
Update Test.php

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Added `use Codeception\Test\Unit` for nicer syntax.

Would be nice if you could do the same for `@var \{{actorClass}}` - I don't know how :-(

### CODE REVIEW

**Comment by RazvanFarte** [comment]
It looks nicer
But does the Unit class contain any function name that might interfere with the current scope?

**Comment by ThomasLandauer** [comment]
Don't know how/why this could be a problem...
But take a look yourself: https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Test/Unit.php

**Comment by DavertMik** [comment]
Sorry, to my preference this doesn't look better
Also it breaks our tests. 
So I'd rather not change this part

**Comment by ThomasLandauer** [comment]
OK, it's not that important. But isn't it a best practice to have all your `use`s on top? See https://www.php-fig.org/psr/psr-12/#41-extends-and-implements

**Pull request closed without merging**
