### PR TITLE
Minor language improvements

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Please help (I'm starting to work on https://github.com/Codeception/Codeception/issues/4231 ):  
I've cloned the project locally, how can I run the tests?

### CODE REVIEW

**Comment by DavertMik** [comment]
Hey, probably this docs can be outdated. There is no need run all tests (no one run them all locally) but for WebDriver tests you need (after you did `composer install`) a web server started as:

```
php -S 127.0.0.1:8000 -t tests/data/app
```

Then open [tests/web.suite.yml](https://github.com/Codeception/Codeception/blob/2.2/tests/web.suite.yml#L5). By default, Firefox is used (but tests are passing only on Selenium 2.53). So probably you need to run tests with `--env chrome` to use Chrome browser:

When you started Selenium with Chrome 

```
./codecept run web
```

**Comment by ThomasLandauer** [comment]
Which `composer install` do you mean? I just cloned the project from GitHub.

`./codecept run web` results in an error message that the command `@php_bin@` is not found. This is probably comming from `codecept.bat` which looks like this:
````bash
@echo off
if "%PHPBIN%" == "" set PHPBIN=@php_bin@
if exist "codecept" goto INTERNAL
if not exist "%PHPBIN%" if "%PHP_PEAR_PHP_BIN%" neq "" goto USE_PEAR_PATH
GOTO RUN
:USE_PEAR_PATH
set PHPBIN=%PHP_PEAR_PHP_BIN%
:RUN
"%PHPBIN%" "@bin_dir@\codecept" %*
:INTERNAL
"%PHPBIN%" "codecept" %*
````

**Comment by DavertMik** [comment]
Yes, you need to 

```
composer install
```

inside a project once you clone it.

Use

```
php codecept
```
to run everything

**Comment by ThomasLandauer** [comment]
Hey, thanks, works now! :-) I updated the docs: https://github.com/Codeception/Codeception/pull/4236

Some questions:

* Do you really mean Selenium **2.53**? Current version of Standalone Server is 3.4.0: http://www.seleniumhq.org/download/
* Is there a generl issue with Firefox? Or is it just that the tests are not being maintained for Firefox?

**Comment by DavertMik** [comment]
@ThomasLandauer 

> Do you really mean Selenium 2.53? Current version of Standalone Server is 3.4.0: 

Feel my pain: https://github.com/Codeception/Codeception/issues/4161 :cry: :sob:

**Comment by XedinUnknown** [comment]
I didn't understand how this PR solves #4231. Could you elaborate on the solution please?

**Comment by ThomasLandauer** [comment]
My guess: While starting to work on https://github.com/Codeception/Codeception/pull/4248, I fixed some minor language errors in the docs along the way ;-)

https://github.com/Codeception/Codeception/pull/4248 was the "answer" to https://github.com/Codeception/Codeception/issues/4231#issuecomment-302943066, but was never finished. If you want to continue on this PR - feel free :-)

**Pull request merged**
