### PR TITLE
Fix issue regarding 'The xxx service is already initialized, you cannot replace it'

### PR DESCRIPTION
**Pull request by DzeryCZ**
Every time I clean /test cache and run API suite the error appears for the first test. Otherwise, it's OK.

The issue was reported here: #4806

### CODE REVIEW

**Comment by Naktibalda** [comment]
In my opinion "Cannot replace" breaks persistent service functionality, so it is worth at least to log a warning with codecept_debug if service cannot be replaced.

**Comment by Naktibalda** [comment]
On a second thought, replacing works with older versions of Symfony, so it would be better to try to set and catch exception if it failed.

**Comment by DzeryCZ** [comment]
Hello,

Thank you for such fast response.
Yep, It seems to be not a correct solution.

Do you think to put the catch inside of `src/Codeception/Lib/Connector/Symfony.php::rebootKernel`?

**Comment by Naktibalda** [comment]
Yes, I think that try catch should be inside foreach loop, around `$this->container->set($serviceName, $service);` statement.

**Comment by DzeryCZ** [comment]
In the end, removing Doctrine configuration from `Functional.suite.yaml` solved the issue for me.

```
- Doctrine2:
            depends: Symfony
            cleanup: true
```

So this change is not needed.

**Pull request closed without merging**
