### PR TITLE
Implement getInternalDomains() for Phalcon modules

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by Naktibalda** [comment]
Have you tested it?

This line of Phalcon connector should be causing issues: https://github.com/Codeception/Codeception/blob/31f1ab321799a785d9df9e96f2cb937907da6d3d/src/Codeception/Lib/Connector/Phalcon.php#L89

I fixed it in this way for ZF2: https://github.com/Codeception/Codeception/commit/aed8585507ac70d4e459fe5ed3af7a0946fee375#diff-864034b1801b1cf25a887b6a5421a4b7L66

**Comment by sergeyklay** [comment]
I'll look at it later. Currently test fails because larval-specific test fails

**Comment by DavertMik** [comment]
restarted builds

**Comment by sergeyklay** [comment]
https://travis-ci.org/Codeception/Codeception/jobs/86062118#L7148 :(

**Comment by janhenkgerritsen** [comment]
I'll look into that Laravel error when I have some time.

**Comment by sergeyklay** [comment]
@Naktibalda Fixed https://github.com/Codeception/Codeception/pull/2681

**Pull request merged**
