### PR TITLE
Update Lumen amLoggedAs to be compatible with 5.2

### LINKED ISSUE #3340: amLoggedAs causes error in Lumen
```
[PHPUnit_Framework_Exception] call_user_func_array() expects parameter 1 to be a valid callback,
    class 'Illuminate\Auth\RequestGuard' does not have a method 'driver'
```
When I try to use amLoggedAs. Changing the function from
```
public function amLoggedAs($user, $driver = null)
{
    if ($user instanceof Authenticatable) {
        $this->app['auth']->driver($driver)->setUser($user);
    } else {
        $this->app['auth']->driver($driver)->attempt($user);
    }
}
```
to
```
public function amLoggedAs($user, $driver = null)
{
    if ($user instanceof Authenticatable) {
        $this->app['auth']->guard($driver)->setUser($user);
    } else {
        $this->app['auth']->guard($driver)->attempt($user);
    }
}
```
fixes the error but I don't have enough experience to know the full ramifications of this change.

### PR DESCRIPTION
**Pull request by a300600st**
Fixes #3340

### CODE REVIEW

**Comment by Naktibalda** [comment]
Thanks, it looks good.
Don't worry about failed build, it wasn't your fault.

**Comment by a300600st** [comment]
How long will it take before this is available via composer?

**Comment by janhenkgerritsen** [comment]
@DavertMik is there a date for the next release?

For now it is possible to install the 2.2 development branch by specifying `2.x-dev` as your Codeception version in your composer.json file.

**Comment by a300600st** [comment]
Thanks! Yeah I'll do that for now (it's 2.2.x-dev btw) I just wasn't sure how to know when I can get back off the dev version.

**Pull request merged**
