### PR TITLE
fix to get right domain host, not the whole url

### PR DESCRIPTION
**Pull request by nathanphan**
problem: Cannot compare

/^http:\/\/mysite\.local$/u with mysite.local in InnerBrowser.php line 202

It happens for Yii1 module only

Please merge it. I need this changes so My test will passed :)

### CODE REVIEW

**Comment by plutov** [comment]
I vote for this PR will be merged!

**Comment by Naktibalda** [comment]
@nathanphan Please replace tabs with spaces, delete empty lines and indent new code correctly.

**Comment by nathanphan** [comment]
@Naktibalda can you check that Travis CI build failed

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///home/travis/.phpenv/versions/5.4.37/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220

**Comment by amashigeseiji** [comment]
If `$template` is defined like `'http://<hoge:\w+>.hoge.com/'`, `parse_url` returns false.

**Comment by nathanphan** [comment]
yeah it will be false

I just wonder why people config their appPath like that.

**Comment by amashigeseiji** [comment]
This PR does not work if the case `$I->amOnPage('http://mysite.local/')` because it will be treated as external domain. It is not expected.
This is the same problem `$I->click('some link')` which href is `http://mysite.local/`.

I think it should be this.

```diff
--- a/src/Codeception/Module/Yii1.php
+++ b/src/Codeception/Module/Yii1.php
@@ -224,8 +224,8 @@ public function _after(TestInterface $test)
      */
     private function getDomainRegex($template, $parameters = [])
     {
-        if (preg_match('#https?://(.*?)/#', $template, $matches)) {
-            $template = $matches[1];
+        if ($host = parse_url($template, PHP_URL_HOST)) {
+            $template = $host;
         }
         if (strpos($template, '<') !== false) {
             $template = str_replace(['<', '>'], '#', $template);
```

This problem is mainly invalid match pattern.
I pointed [here](https://github.com/Codeception/Codeception/issues/3581#issuecomment-251861095), the problem is `Yii::app()->request->getHostInfo()` returns `http://mysite.local` (without trailing slash), but `Yii1::getDomainRegex` expects string with trailing slash([code](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Module/Yii1.php#L227)).
Regex pattern `'#https?://(.*?)/#'` does not match `http://mysite.local` because trailing slash does not exist.
This is the reason `Yii1::getDomainRegex` returns invalid pattern, I think.

another solution is:
```diff
--- a/src/Codeception/Module/Yii1.php
+++ b/src/Codeception/Module/Yii1.php
@@ -224,8 +224,8 @@ public function _after(TestInterface $test)
      */
     private function getDomainRegex($template, $parameters = [])
     {
-        if (preg_match('#https?://(.*?)/#', $template, $matches)) {
+        if (preg_match('@^(?:https?://)?([^/]+)@i', $template, $match) {
             $template = $match[1];
         }
         if (strpos($template, '<') !== false) {
             $template = str_replace(['<', '>'], '#', $template);
```

I misunderstood that `$rule->template` on [here](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Module/Yii1.php#L254) is like `'http://<subdomain:\w+>.mysite.local/<action:\w+>'`,
but it is `'http://<subdomain>.mysite.local/<action>'`.
So `parse_url` is behave as expected, and `parse_url` looks more cool for me than regex.

**Comment by Naktibalda** [comment]
@amashigeseiji Could you make a PR? Your solution looks more correct.

**Comment by Naktibalda** [comment]
Replaced by #3597

**Pull request closed without merging**
