### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by DavertMik**
Implementation of Examples in Cest format and [Scenario Outlines](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines) for Gherkin. 
Examples are DataProviders alternative for scenario driven tests. 

Examples can be passed as doctrine-style annotations, json-object or json-array.

```php
    /**
     * @example(path=".", file="scenario.suite.yml")
     * @example(path=".", file="dummy.suite.yml")
     * @example(path=".", file="unit.suite.yml")
     */
    public function filesExistsAnnotation(ScenarioGuy $I, Example $example)
    {
        $I->amInPath($example['path']);
        $I->seeFileFound($example['file']);
    }


    /**
     * @example { "path":".", "file":"scenario.suite.yml" }
     * @example { "path":".", "file":"dummy.suite.yml" }
     * @example { "path":".", "file":"unit.suite.yml" }
     */
    public function filesExistsByJson(ScenarioGuy $I, Example $example)
    {
        $I->amInPath($example['path']);
        $I->seeFileFound($example['file']);
    }

    /**
     * @example [".", "scenario.suite.yml"]
     * @example [".", "dummy.suite.yml"]
     * @example [".", "unit.suite.yml"]
     */
    public function filesExistsByArray(ScenarioGuy $I, Example $example)
    {
        $I->amInPath($example[0]);
        $I->seeFileFound($example[1]);
    }
```

See included file.

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by GaryJones** [comment]
Could you please give an example of what the example `.yml` files would look like please?

Simply:

```yml
path: ...
file: ...
```
?

**Comment by DavertMik** [comment]
You don't need any files to use examples. 

```
@example(path=".", file="scenario.suite.yml")
```

is just a fragment of internal test suite. We pass 2 parameters: `path` and `file`. Then we use them in tests like `$example['path']`.

The same way you can pass absolutely any param:

```php
/**
@example(color="brown")
@example(color="black")
*/
function colors(\ColorsTester $I, \Codeception\Example $example)
{
    $I->seeColorInPalette($example['color']);
}
```

**Comment by maff** [comment]
Is there a way to generate the examples via code  - e.g. `@example` referencing a method which will be called to generate example data (similar to the `@dataProvider` annotation for PHPUnit)?

**Comment by akiessling** [comment]
I have the same question as @maff : can i provide the examples via code? I want to implement something similar like in #1090, but when running this in Jenkins with xunit output, i only get one testrun with all urls.

**Comment by mikeuding** [comment]
Yes, via this extension: https://github.com/edno/codeception-dataprovider

**Comment by GaryJones** [comment]
I just wanted to follow-up here with how I've been using this functionality. Here's a small part of my `RedirectsCest.php`:

screenshot 2016-11-02 16 47 41

The multiple functions are to allow specific groups of URLs to be tested, so that re-checking to see if a specific`@example` data now passes, doesn't mean running the whole Cest.

Clearly, the downside is, all of the functions are basically the same, and call a separate private method.

It's not ideal, but it works for me.

**Comment by alexpts** [comment]
How I Can pass php constant to @example?

**Comment by edno** [comment]
Can be done using [@dataprovider](https://github.com/Codeception/Codeception/pull/3737) annotation.

**Pull request merged**
