### PR TITLE
don't fire TEST_AFTER on conditional failure, fixes #1647 #1354 and #111...

### LINKED ISSUE #1647: REST module throws execeptions after using "canSeeResponseContainsJson"
I created a simple test to call a URL and then test if I can:
```php
$I->canSeeResponseContainsJSON(array('status'=>'OK'));
```
When I test for that, and the response contains the array('status'=>'OK') everything is OK

BUT, if I change the code to be:
```php
$I->canSeeResponseContainsJSON(array('status'=>'OK2'));
//OR
$I->canSeeResponseContainsJSON(array('status1'=>'OK'));
```
REST.php throws an exception the next time I try to issue a $I->sendGET
```bash
PHP Fatal error:  Call to a member function request() on a non-object in vendor/codeception/codeception/src/Codeception/Module/REST.php on line 380
```
Here is my test
```
    $params['url'] = 'http://localhost.com/2010/06/01/travel/escapes/dan_is_testing.html';
    $I->sendPOST("http://$host/svc/bitly/shorten", $params);
    $I->canSeeResponseIsJson();
    $I->canSeeResponseContainsJSON(array('status'=>'OK2'));
    unset($params);
    $params['url'] = 'http://localhost.com/2010/06/01/travel/escapes/dan_is_testing.html';
    $params['start_date'] = '2010-06-02';
    $params['end_date'] = '2010-06-02';
    $I->sendGET("http://$host/svc/bitly/urlstats", $params); // **THOWS ERROR HERE**
    $I->seeResponseIsJson();
    $I->seeResponseContainsJSON(array('status'=>'OK'));
```
I'm using codeception 2.0.9
> php -v
PHP 5.5.13 (cli) (built: Sep  8 2014 14:41:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
> composer -V
Composer version 1.0-dev (c58b7d917c65692eeb00c22b2fbaaa251cb390dc) 2015-01-05 16:31:16

### PR DESCRIPTION
**Pull request by schmunk42**
I had the same problems like described in #1647 #1354 and #1111 

Please review this PR, as I have no deep understanding of Codeception's internals, but from the explanations in the issues, the fix would look logical to me.

### CODE REVIEW

**Comment by zbateson** [comment]
Hi @schmunk42 - can/cant methods are generated, so you won't see tests in unit tests for the modules (because the can/cant methods don't actually exist on them).  I had written some tests for this exact problem but I think the idea is to put this fix in a coming release.  

You can see the tests I had created here if interested: https://github.com/zbateson/Codeception/commit/df2960da6fc515aa6378b701e341405405ee1658 which is pretty much the same as your PR but with some testing, and will most likely be a part of 2.1, not 2.0.

**Comment by zbateson** [comment]
Unless @DavertMik would be happy to merge this, and have the test code only be a part of 2.1 which I'm all for, as it would allow us to use can/cant before 2.1 :)

**Comment by schmunk42** [comment]
@zbateson Thanks for your info :) Is your code already in 2.1?

**Comment by zbateson** [comment]
It isn't yet, I hadn't had a chance to submit a pull request to master - I'm hoping to have some time in the next 4/5 days to do so.  That commit was written against 2.0 so I'll have to check if the test code would need any modification before submitting.

**Comment by zbateson** [comment]
It was decided to merge my pull request against 2.0 after all.  It's the same as yours just with the added tests :)

Thank you

**Pull request closed without merging**
