### PR TITLE
Fixed "Call to undefined method Symfony\Component\HttpFoundation\Request::route()"

### PR DESCRIPTION
**Pull request by jedrzej**
This is a fix to #1748.

### CODE REVIEW

**Comment by constb** [comment]
there's an easier way to do this: ``\Illuminate\Http\Request::createFromBase($request)``

**Comment by duxet** [comment]
:+1:

**Comment by DavertMik** [comment]
Thanks
@janhenkgerritsen can I merge this?

**Comment by tomschlick** [comment]
:+1: please get this in soon

**Comment by devinfd** [comment]
This needs to be merged in asap please. test will not run otherwise with kind of paralyzes development

**Comment by janhenkgerritsen** [comment]
@DavertMik you should merge #1756 instead.

**Comment by aitiba** [comment]
For all the people with problem with this issue:

- Go to the root directory of your laravel application.
- Open this file: vendor/codeception/codeception/src/Codeception/Lib/Connector/Laravel5.php
- Comment line 67 with this content: $this->httpKernel->terminate($request, $response);
- After that line, add the following: $this->httpKernel->terminate(Request::createFromBase($request), $response);

This way I fixed the issue.

**Comment by mikeerickson** [comment]
+1 on this one!  Guess the Laravel5 module was not tested against release version of Laravel 5, thinking everyone should be receiving this error

**Comment by mikeerickson** [comment]
@aitiba Thanks for defining the fix, this will suffice in the interim...

**Comment by janhenkgerritsen** [comment]
You shouldn't be commenting on this closed issue. As you can see I already provided a fix for this issue in #1756, the fix of altiba is just that. We are now waiting that the fix in #1756 will be released.

Furthermore, the Laravel5 module *was* tested against Laravel 5, by means of a sample application you can find at https://github.com/janhenkgerritsen/codeception-laravel5-sample. However, since the release of Laravel 5 there have been 13 patch releases, and one of those broke the module. So please read before you comment something that is blatantly wrong.

**Comment by mikeerickson** [comment]
@janhenkgerritsen I am not sure if you comment was directed at me (for commenting) but your comment about being blatantly wrong is a little misguided.   How about a simple polite response, instead of getting so defensive.

===

So far as I can see (updated to latest version of Codeception along with rebuilding the modules so I pull in latest Laravel5 module) this is still having issues.

http://d.pr/i/DcQj

Now, if you would prefer I create a new issue -- will do so now!

**Comment by janhenkgerritsen** [comment]
You do not need to create a new issue, there already is an issue covering this problem, you can find it a #1756. This is the second time I have to mention this to you, that is what I meant with my previous comment by reading before commenting.

Maybe my wording in the previous comment was a little strong, but I did not really like your insinuation of not testing the module, since it took a considerable amount of time to create the sample application.

**Comment by mikeerickson** [comment]
@janhenkgerritsen Completely lost in translation, I guess I should have included an emoji    This happens WAY WAY WAY too much on the internet (text message) scene.   I battle this same issue with my kids, etc.    No worries, I just want things to work ;=)

**Pull request closed without merging**
