### PR TITLE
Simplify Lib classes

### PR DESCRIPTION
**Pull request by TavoNiievez**
300 additions & 419 deletions.

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by SamMousa** [comment]
- [ ] Trusted contributor
- [ ] Changes look reasonable
- [ ] Tests pass

I'd say just merge this!

**Comment by SamMousa** [comment]
@TavoNiievez what's your confidence level on this? Can I go ahead and merge this or do you feel there's specific things that need an extra good look?

**Comment by aanieves** [comment]
@SamMousa Well, I had gotten used to Naktibalda checking me this kind of PR where I change many things at once, since he is (or was?) who had a more general knowledge about what is susceptible to generate problems if changed, even if the tests are going OK.

If I had to answer your question I would say 85% sure that all changes were applied safely.

**Comment by TavoNiievez** [comment]
@SamMousa Well, I had gotten used to Naktibalda checking me this kind of PR where I change many things at once, since he is (or was?) who had a more general knowledge about what is susceptible to generate problems if changed, even if the tests are going OK.

If I had to answer your question I would say 85% sure that all changes were applied safely.

**Comment by SamMousa** [comment]
I'm gonna defer to him, and gonna ping him hoping he'll give the okay then! @Naktibalda you up for reviewing this?

**Comment by TavoNiievez** [comment]
I rechecked the changes I introduced in this PR and I think it is ready.

I'm going to continue with another folder so I'm going to go ahead with this.

**Pull request merged**
