### PR TITLE
Pass body request into yii2 request

### PR DESCRIPTION
**Pull request by m8rge**
This allows to send Xml payload:
```php
$i->haveHttpHeader('Content-Type', 'application/xml');
$i->sendPOST('/v1/door/new-goods', $xmlString);
```

### CODE REVIEW

**Comment by samdark** [comment]
Have you tried it with Yii code from master?

**Comment by m8rge** [comment]
@samdark I tested this code with 2.0.3

**Comment by samdark** [comment]
How to reproduce the issue?

**Comment by m8rge** [comment]
This pull request is not actually bugfix, but feature.

Without this pull, you can't post xml payload like this:
```php
public function addNewItem(FunctionalTester $i) {
    $xml = <<<EOT
<root>
    <goods>
        <productId>1</productId>
        <placeId>1</placeId>
        <boxId>2</boxId>
    </goods>
</root>
EOT;
    $i->sendPOST('/v1/door/new-goods', $xmlString);
}
```

**Comment by samdark** [comment]
What will happen with passing arrays?

**Comment by m8rge** [comment]
It will be assigned to $_POST variable. Then, array will be returned as is in https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L370
Please note, that parsers in L382 are not reached.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
