### PR TITLE
Don't fail test validation when exec function is disabled

### LINKED ISSUE #3324: Fatal warning in Parser::validate
codecept version 2.2.2
execute codecept.phar run command prompt:
[PHPUnit_Framework_Exception]  Undefined variable: output

### PR DESCRIPTION
**Pull request by Naktibalda**
Fixes #3324 

I haven't tested this change - I made it using GitHub editor.

### CODE REVIEW

**Comment by DavertMik** [comment]
Do you know how can I test it? I don't know how to disable `exec` in pragmatic way )

**Comment by Naktibalda** [comment]
add `disable_functions=exec` to php.ini

**Comment by DavertMik** [comment]
This doesn't fix this issue :(

**Comment by DavertMik** [comment]
But when I looked to original issue it looks it is better to merge this PR. This won't solve the problem but at least will not stop with `$code` and `$output` variables undefined.

**Comment by Naktibalda** [comment]
@DavertMik in https://gist.github.com/k4kuz0/74c8b11bf424e5d61070da460d93e1ab it looks like convertWarningsToExceptions is set to false.

**Comment by mklemarczyk** [comment]
Problem is still valid for version 2.1.x.

**Comment by Naktibalda** [comment]
Have you got a good reason to not upgrade to 2.2?

**Comment by mklemarczyk** [comment]
The yii2 framework in version 2.0.9 (current stable) require Codeception 2.1.x version for test execution. I do not have any possibility to change that.

**Comment by Naktibalda** [comment]
@DavertMik what do you think about backporting more bugfixes (me) and making one more release of 2.1(you) ?

**Pull request merged**
