### PR TITLE
Fixes issue with guzzle body contents being truncated

### PR DESCRIPTION
**Pull request by Shardj**
Fixes issue #5722

### CODE REVIEW

**Comment by joelperry93** [comment]
@DavertMik this PR fixes broken tests for us. Would really appreciate feedback when you can :)

**Comment by Naktibalda** [comment]
I see no difference between `__toString` and `getContents`, they both call stream_get_contents
https://github.com/guzzle/psr7/blob/1.6.1/src/Stream.php#L76-L99

Could you add a failing test to https://github.com/Codeception/Codeception/blob/3.1/tests/unit/Codeception/Module/PhpBrowserRestTest.php ?
You can add a new endpoint which generated a long enough response to https://github.com/Codeception/Codeception/tree/3.1/tests/data/rest

**Comment by Shardj** [comment]
Using `docker-compose build` within the tests directory fails for me with 

`ERROR: Service 'codecept' failed to build: The command '/bin/sh -c composer install --prefer-dist --no-interaction --optimize-autoloader --apcu-autoloader' returned a non-zero code: 1`

So I'm unable to run the tests I've written. Would be appreciated if you know what the issue is, writing a test to try and get to the bottom of my issue would be helpful.

The tests in our project that are failing are a bit temperamental, sometimes they seem fine and other times the json content from the stream is truncated. I've used xdebug to confirm that the issue is reading from the stream and that the content being actually sent back from our api is fine. Since I made the change found within this PR I've had no further test failures. But I can't confirm for sure that this is a fix because as said our test are a bit temperamental.

__toString and getContents aren't exactly the same, __toString does an extra typehint and it uses $this->seek(0) before stream_get_contents. But I can't see why it's making a difference.

**Comment by Shardj** [comment]
```
[RuntimeException]
  Could not scan for classes inside "tests/cli/_steps" which does not appear to be a file nor a folder
```
Some more detail on my docker-compose build failure

**Comment by Shardj** [comment]
Ok seems like 'sam' added some autoloaders to bad paths back in august, removing them seems to fix the issue. That probably wants a separate PR as I haven't looked into the purpose of autoloading the tests/*/_steps/ files

**Comment by Shardj** [comment]
`docker-compose run --rm codecept run unit`

Seems like out of the 1122 unit tests 217 error and 30 fail? Seems like a crazy number all things considered. I'm also unable to find an easy way to xdebug my test, doesn't look like it's supported for some reason.

**Comment by Shardj** [comment]
Lots of failed curl to localhost errors. Seems like the docker environment is really messed up

**Comment by Naktibalda** [comment]
Sorry @Shardj , Codeception 3.1 is out of support.
Codeception 4.0 will be functionally identical, but modules are extracted to separate repositories.
Please make a new pull request to https://github.com/Codeception/module-phpbrowser

I've never tested Codeception using docker,
in order to test the module you need php cli (you can probably install php-cli docker image),
and start builtin php daemon:
`php -S 127.0.0.1:8000 -t tests/data/app >/dev/null 2>&1 &` - for PhpBrowserTest.php
or `php -S 127.0.0.1:8010 -t tests/data/rest >/dev/null 2>&1 &` - for PhpBrowserRestTest.php

**Comment by Shardj** [comment]
Using Codeception 4.0 within our project results in errors because the REST module is missing

**Comment by Naktibalda** [comment]
You must install all modules used by your testsuite separately now,
@DavertMik is working on a script to automate that process.

**Comment by SamMousa** [comment]
@Shardj I'm closing this since it seems stale.
Feel free to create a new issue / PR for 4.1 in case you still have the issue.

**Pull request closed without merging**
