### PR TITLE
Quote PostgreSql names (2.0 branch)

### PR DESCRIPTION
**Pull request by satahippy**
Quote PostgreSql names on delete and lastInsertId
Issue #1916

### CODE REVIEW

**Comment by DavertMik** [comment]
Oh, @satahippy, could you review the alternative PR https://github.com/Codeception/Codeception/pull/1912
I'm not sure for the best solution that should be merged.

**Comment by satahippy** [comment]
@DavertMik, there is not much difference)
#1919 quotes in `PostgreSql::lastInsertId`
#1912 quotes in `Db::getPrimaryKeyColumn`
maybe merge both?

**Comment by DavertMik** [comment]
@satahippy oups, I can't merge both, they are conflicting, and auto-merge doesn't work once I merged that.
Could you merge and resend PR?

**Comment by satahippy** [comment]
@DavertMik, done

**Pull request closed without merging**
