### PR TITLE
Improved documentation for PhpBrowser->submitForm()

### PR DESCRIPTION
**Pull request by SimonEast**
I found that `submitForm()` was a little confusing to me at first, so I've updated the documentation to hopefully help out others.

### CODE REVIEW

**Comment by SimonEast** [comment]
Oh, actually, perhaps I need to make changes to the actual source code of the function, not the doc file, is that correct?  I'll have to update my PR.

**Comment by DavertMik** [comment]
> Oh, actually, perhaps I need to make changes to the actual source code of the function, not the doc file, is that correct? I'll have to update my PR.

Yes, you need to change that description in phpdoc of WebInterface

**Comment by SimonEast** [comment]
OK, I've updated the patch and put the documentation into the correct place this time. :-)  Please let me know if it's all OK.

Should I also regenerate the MD doc files somehow?  Or can someone do that for me?

Simon.

**Comment by zbateson** [comment]
Yeah, the MD files get generated automatically when a release is pushed out - thanks again I think it's much better.

**Pull request merged**
