### PR TITLE
Group files testcase

### LINKED ISSUE #3562: Group Files with exact test not working with @example
Hello,

Again one case that doesn't work with group files :(

**api.suite.yml**
```
groups:
    group3: tests/_data/group3
```

**tests/api/welcomeCest.php**
```
class welcomeCest
{
    /**
    * @example (hello="boy")
    * @example (hello="girl")
    */
    public function tryToTest(ApiTester $I, \Codeception\Example $example)
    {
    }
}
```
### This one is NOT working

**tests/_data/group3**
`tests/api/welcomeCest.php:tryToTest`

**./vendor/bin/codecept run api -g group3**
```
Codeception PHP Testing Framework v2.2.5
Powered by PHPUnit 5.5.5 by Sebastian Bergmann and contributors.
[Groups] group3 

Api Tests (0) --------------------------------------------


Time: 77 ms, Memory: 9.50MB

No tests executed!
```
Codeception 2.2.5 is not able to execute a group file that exactly precise the test case with dataprovider.

### This one is working
Without this exact test case it's working well

**tests/_data/group3**
`tests/api/welcomeCest.php`

**./vendor/bin/codecept run api -g group3**
```
Codeception PHP Testing Framework v2.2.5
Powered by PHPUnit 5.5.5 by Sebastian Bergmann and contributors.
[Groups] group3 

Api Tests (2) 
---------------------------------------------------------------
✔ welcomeCest: Try to test | "boy" (0.00s)
✔ welcomeCest: Try to test | "girl" (0.00s)
---------------------------------------------------------------


Time: 80 ms, Memory: 9.50MB

OK (2 tests, 0 assertions)
```

I will work on it to fix it.

### PR DESCRIPTION
**Pull request by eXorus**
Fix #3562

### CODE REVIEW

**Comment by eXorus** [comment]
@DavertMik I would like to have this PR merged with the next version.

The only solution I saw is to delete tests to be able to be merged .... Are you agree with that ?

See #3542 with all my tests. I think my PR is OK in Linux and Windows but nobody are succeed to add test about group files with Windows.

**Comment by eXorus** [comment]
Ready to merge without adding tests

**Comment by eXorus** [comment]
No 2.2.6 is out without this PR ;)

Are you waiting something from me @DavertMik  or @Naktibalda ?

**Comment by Naktibalda** [comment]
Your test was failing because of a yet another double slash issue (double backslash this time)
```
Check if: C:\projects\codeception\tests\data\sandbox\tests\scenario\\ExamplesCest.php:filesExistsAnnotation
Starts with: C:\projects\codeception\tests\data\sandbox\tests\scenario\ExamplesCest.php:filesExistsAnnotation
```
https://ci.appveyor.com/project/Naktibalda/codeception/build/1.0.1#L302

**Comment by eXorus** [comment]
Thanks @Naktibalda for your help.

**Pull request merged**
