### PR TITLE
Fix for issue #5464 - moved remote c3 calls for code coverage to RemoteServer

### PR DESCRIPTION
**Pull request by pgl**
Fix for issue #5464

### CODE REVIEW

**Comment by Naktibalda** [comment]
Not a bug.

**Comment by pgl** [comment]
The Semaphore test failed on the test `WebDriverTest:testChangingCapabilities`. I've run this test locally a few times and tried to figure out what might be wrong, but I really can't figure out what might be the issue.

Any help would be appreciated.

**Comment by pgl** [comment]
Oh... how comes it was closed?

**Comment by Naktibalda** [comment]
You raised #5489 which is still open.

**Comment by pgl** [comment]
OK, thanks. :)

**Pull request closed without merging**
