### PR TITLE
Add yii events for app run

### PR DESCRIPTION
**Pull request by TriAnMan**
Add yii2 application events as mentioned in #1262 see: https://github.com/Codeception/Codeception/issues/1262#issuecomment-52208406

### CODE REVIEW

**Comment by samdark** [comment]
@TriAnMan is it still valid?

**Comment by TriAnMan** [comment]
I think so. I use my own hacks to overcome the most issues I've posted. Have to recheck my source code for this particular issue.

**Comment by samdark** [comment]
Thanks!

**Comment by TriAnMan** [comment]
@samdark I've reviewed my code and found that I not use any workarounds for this issue.
As I remember I pulled it in case of ivestigation of tests ouptut buffers issue (#1262).
To be more precise: I've found that Codeception workflow differs from the yii's one and decided to make this PR. I have no particular issues with it because I have no events that should be run on an application startup. But someone may have.

**Comment by Naktibalda** [comment]
2.0 is dead, could you make a pull request to 2.1?

**Pull request closed without merging**
