### PR TITLE
Change the namespace for the example command.

### PR DESCRIPTION
**Pull request by sd-tm**
To make it more personalized.

### CODE REVIEW

**Comment by DavertMik** [comment]
Please fix the test:

```
PHP Fatal error:  Class 'Codeception\Command\MyCustomCommand' not found in /home/travis/build/Codeception/Codeception/tests/unit/Codeception/Command/MyCustomCommandTest.php on line 19
```

**Comment by sd-tm** [comment]
*grr* i have forget it.

**Comment by sd-tm** [comment]
The test continuous-integration/travis-ci/pr  was not my fault :wink:

**Comment by DavertMik** [comment]
thanks, build passed

**Pull request merged**
