### PR TITLE
always disconnect before connect when reconnect is set

### PR DESCRIPTION
**Pull request by ashnazg**
(edit: removed the 'is already connected' check behavior)

### CODE REVIEW

**Comment by Naktibalda** [comment]
What issue does this change solve?

**Comment by ashnazg** [comment]
Small runtime optimization.  While working on #5069, I saw more runtime connect calls than I expected.  

Since I reasoned that the target db doesn't change during an execution (unlike browser changes via `env` customizations), it seemed unnecessary to connect again when a connection was already made. Again, this is when the `reconnect` option is *not* enabled.

However, **if** there is a viable use case of targeting multiple databases in the same config via `env`, then this change should *not* be accepted.

**Comment by DavertMik** [comment]
Makes sense to me. 
However, a test may run for a long time and connection can be lost. Maybe some healthcheck queries should be sent instead?

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
