### PR TITLE
Move kernel booting and container set up into _initialize() method

### PR DESCRIPTION
**Pull request by Franua**
I faced a situation when I needed to load and use some of my Symfony2 project's services in _beforeSuite() to prepare some needed data, obviously, before suit is running. I couldn't do that because current implementation loads kernel and set up container only before a test (in the _beforeTest() method).
I also created an issue about that (according to https://github.com/Codeception/Codeception/wiki/Git-workflow-for-Codeception-contributors) - https://github.com/Codeception/Codeception/issues/2490
Tests passed with my changes.

### CODE REVIEW

**Comment by tiger-seo** [comment]
Afaiu, with beforeTest kernel is a brand new for each test, so tests doesn't influence each other, but with beforeSuite there will be only one kernel for all tests, so it might lead to potential issues

**Comment by tiger-seo** [comment]
Ok, it's not about kernel, but client, nonetheless, the idea is the same

**Comment by Franua** [comment]
Client's initialization remains in _before(). I moved only kernel loading and container's initialization into __initialize().

**Comment by Franua** [comment]
Kernel loading is based (dependent) on config. I don't think config is being changed every test.

**Comment by Naktibalda** [comment]
The tests pass, so this change is not breaking them.

Laravel modules instantiate app and client in _initialize.

If this change is accepted, I will do the same for ZF1 and ZF2.

**Comment by Naktibalda** [comment]
All tests are using the same instance of kernel already,
bootKernel only creates a new instance if $this->kernel is null.

**Pull request merged**
