### PR TITLE
Base href tag and relative path functionality.

### LINKED ISSUE #3764: PhpBrowser does not honouring <base href=""> meta tag
#### What are you trying to achieve?
By using PhpBrowser trying to click an anchor link.
page url is in 'http://example.com/sitefolder/folder/service/panel' format.
page is containing `<base href="http://example.com/sitefolder/folder/"/>` tag.
anchor href attribute is  "service/action".
after click operation current URL must be 'http://example.com/sitefolder/folder/service/action.
 
#### What do you get instead?
current URL becomes 'http://example.com/sitefolder/folder/service/service/action' as if there is no `<base href="">` meta tag in the page. From a normal browser link is working.

> Provide test source code if related

```php
    $I->amOnPage('/service/panel');
    $I->seeLink('Action', 'service/action');
    $I->click(['link' => 'Action']);
    $I->seeCurrentUrlEquals('http://example.com/sitefolder/folder/service/action');
```
### Details

* Codeception version: Codeception version 2.2.6
* PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
* Operating System: linux mint 18.0
* Installation type: Phar
* List of installed packages (`composer show`) : none
* Suite configuration: 

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - Asserts
        - PhpBrowser:
            url: http://example.com/sitefolder/folder
        - \Module\RESTAPI:
            depends: PhpBrowser
        - Db:
            dsn: 'pgsql:host=localhost;dbname=dbname'
            user: 'username'
            password: 'password'
            dump: dump.sql
            populate: true
            cleanup: false
            reconnect: false
```

### PR DESCRIPTION
**Pull request by hubbyist**
fixes #3764

Signed-off-by: Mehmet Durgel <md@legrud.net>

### CODE REVIEW

**Comment by DavertMik** [comment]
I like the code, I like the tests, but Travis and Appveyor don't.
Please fix the tests

**Comment by hubbyist** [comment]
Will do ASAP.

**Comment by hubbyist** [comment]
I am still not sure about moving tests from TestsForWeb to TestsForBrowsers to make them pass 
``` tests/unit/Codeception/Module/FrameworksTest.php ``` but couldn't find a work around to 
```[Exception] URL, :8000/basehref, not found.``` error.

**Comment by Naktibalda** [comment]
Change `<base href="http://localhost:8000/basehref/"/>` to `<base href="/basehref/"/>`

**Comment by hubbyist** [comment]
I made the changes and it worked for testClickOnPageWithBaseHrefTagInSubFolder(). But for testClickOnPageWithBaseHrefTag() I get ``` [Exception] URL, /basehref, not found.  ``` error. It seems as if trailing slash is missing. Committing as is.

Do frameworks use a different click function?

**Comment by DavertMik** [comment]
Closed in favor of #3771
Thanks for all your efforts and fixes but PR from @Naktibalda has passing tests and looks simpler. If you have suggestions and improvements you can send them as PR to updated 2.2 branch.

And don't stop contributing :+1:

**Pull request closed without merging**
