### PR TITLE
add crap4j support

### PR DESCRIPTION
**Pull request by gimler**
Add support for crap4j reports.
see also #1627

C3 PR https://github.com/Codeception/c3/pull/28

### CODE REVIEW

**Comment by gimler** [comment]
@Naktibalda i am actually not sure why it fails on 5.5. I will try to get a docker php5.5 up and running and find the bug ;(

**Comment by Naktibalda** [comment]
Probably you don't need PHP 5.5 to reproduced this failure.
5.5 build runs `composer update --prefer-lowest` so a fix could be to raise the lowest supported version of relevant library in composer.json
```json
"phpunit/php-code-coverage": ">=2.1.3 <5.0",
```
[2.2.3](https://github.com/sebastianbergmann/php-code-coverage/blob/master/ChangeLog-2.2.md#223---2015-09-14) looks like a good candidate

> Fixed #382: Crap4J report generates incorrect XML logfile

**Comment by DavertMik** [comment]
Thanks, good additions.

Could you explain the benefits of this format?

**Comment by gimler** [comment]
We use booth coverage.xml for clover php report and coverage. And crap4j for https://wiki.jenkins-ci.org/display/JENKINS/Crap4J+Plugin.

**Comment by gimler** [comment]
Crap4j Plugin is also used in the http://jenkins-php.org project.

**Comment by DavertMik** [comment]
Ok, thanks for the information. Good job!

**Comment by gimler** [comment]
Thanks

**Comment by gimler** [comment]
@DavertMik please also merge the https://github.com/Codeception/c3/pulls PRs

**Pull request merged**
