### PR TITLE
[Yii2] Fixed `@webroot` directory creation

### PR DESCRIPTION
**Pull request by DavertMik**
Proposed by @dmitry-kulikov

### CODE REVIEW

**Comment by samdark** [comment]
Looks good to me.

**Comment by githubjeka** [comment]
Don't work for me. :(
> Codeception version 2.2.6

**Comment by githubjeka** [comment]
If use command ` $I->click('save-user');` `@webroot` will be created...

**Comment by githubjeka** [comment]
The code ` return $this->redirect(['view', 'id' => $user->id]);` will run after click ... 
Replace to `return $this->render('view', ['model' => $user,]);` and `@webroot` doesn't created.
What could be the problem?

**Comment by samdark** [comment]
No idea.

**Comment by githubjeka** [comment]
After redirect on page uses:
```
$this->registerJsFile('@web/js/d3Temperature.js',
    ['depends' => [\yii\web\JqueryAsset::className(), \common\assets\D3Asset::className()]]);
```

P.S. How use XDebug with codecept ?

**Comment by githubjeka** [comment]
@samdark 
this PR:
```php
$this->app->set('assetManager', Stub::make('yii\web\AssetManager', ['bundles' => false]));
```

To fix my issue need:
```php
$this->app->set('assetManager', Stub::make('yii\web\AssetManager', ['bundles' => false, 'publish'=>function(){}]));
```

**Comment by githubjeka** [comment]
Do you use the function `mockAssetManager()` in Acceptance Testing ?

**Comment by lukascernydis** [comment]
Hi, I have discovered the reason why @webroot directory is created.
When AssetManager is mocked, it's basePath and baseUrl is set with an alias, that don't get translated.

```
 basePath = "@webroot/assets"
 baseUrl = "@web/assets"
```
The following change in codeception Yii connector fixed all my issues
**codeception/base/src/Codeception/Lib/Connector/Yii2.php** 
```
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager', ['bundles' => false]));
    $this->app->getAssetManager()->basePath = Yii::getAlias($this->app->getAssetManager()->basePath);
    $this->app->getAssetManager()->baseUrl = Yii::getAlias($this->app->getAssetManager()->baseUrl);
}
```

@samdark Is this fix ok?

**Comment by githubjeka** [comment]
No, hasn't fix this issue https://github.com/Codeception/Codeception/issues/3706
In Yii2 tests `@webroot` is root `codeception.yml` location

**Comment by lukascernydis** [comment]
How about this? `bundles => false` is not necessary anymore.

```
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager'));
    $this->app->getAssetManager()->basePath = realpath(Yii::getAlias($this->app->getAssetManager()->basePath));
    $this->app->getAssetManager()->baseUrl = Yii::getAlias($this->app->getAssetManager()->baseUrl);
}
```

I have tried with this and works like a charm
```
$this->registerJsFile('@web/js/iCheck.js', ['depends' => [
    \yii\web\JqueryAsset::className(), 
    \yii\bootstrap\BootstrapAsset::className()
]]);
```

realpath() usage is to translate to absolute path to fix my another problem with SCSS convereter error

**Comment by githubjeka** [comment]
With your code:
image

**In Yii2 tests `@webroot` is root `codeception.yml` location**

Correct fix is setting `basePath` & `baseUrl` of  assetManager in your confguration of Application 
See https://github.com/yiisoft/yii2-app-advanced/pull/219 , for example.

**Comment by lukascernydis** [comment]
With `basePath` and `baseUrl` set in config, settings are correct until this code occurs:

`$this->app->set('assetManager', Stub::make('yii\web\AssetManager'));`

before:
`basePath = "C:\web\domains\yii.dev\config/../assets"`

after:
```
basePath = "@webroot/assets"
baseUrl = "@web/assets"
```
This aliases will never get translated.

I am currently using basic template with codeception.yml in @webroot. 
I will try to fix it on advanced template too.

**Comment by githubjeka** [comment]
@see https://github.com/Codeception/Codeception/pull/3742

**Comment by lukascernydis** [comment]
Yes, this is definitely the solution. 

I was hoping for some global codeception fix so will avoid to overriding codeception files locally.

**Comment by githubjeka** [comment]
I tried to search this fix too. If you will find - welcome to PR.

**Comment by githubjeka** [comment]
@lukascernydis see also https://github.com/Codeception/Codeception/pull/3719#discussion_r87517149

**Comment by lukascernydis** [comment]
I will try to fix it in both templates in the evening. All fixes that I found are only curing the symptoms - not solving the issue.

Why do we actually need to mock the asset manager?

Thanks for your effort :-)

**Comment by githubjeka** [comment]
> Why do we actually need to mock the asset manager?

A first functional test is slow for fresh application, because assertManager will generate files, which in functional case not used (https://github.com/Codeception/Codeception/issues/3706#issuecomment-260115289)

**Comment by lukascernydis** [comment]
How about this? All bundles being registered are replaced with empty bundle so nothing get published.

```
private function mockAssetManager()
{
    $this->app->set('view', Stub::make('yii\web\View', [
        'registerAssetBundle' => function() {
            return new AssetBundle();
        }
    ]));
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager', ['bundles' => false]));
}
```

**Comment by githubjeka** [comment]
If you mock component then component can't be configurate from config. AssetManager can be mocked for this case, but View - no, I don't think.

**Comment by lukascernydis** [comment]
Hope this will be the last try. Empty bundles like in previous attempt, but now in AssetManager. Works with dependencies as well.

private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager', [
        'bundles' => false,
        'getBundle' => function () {
            return Yii::createObject('yii\web\AssetBundle');
        },
    ]));
}

**Comment by githubjeka** [comment]
This broked my tests by
>  [yii\base\UnknownMethodException] Calling unknown method: yii\web\AssetBundle::addLanguage()

**Comment by lukascernydis** [comment]
This should fix error when using custom AssetBundles

```
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager', [
        'bundles' => false,
        'getBundle' => function ($name) {
            if (!class_exists($name)) {
                $name = 'yii\web\AssetBundle';
            }

            return Yii::createObject($name);
        },
    ]));
}
```

**Comment by githubjeka** [comment]
I have the code
```php
$this->assetManager->publish('@common/assets/network-data-save/readout.js');
```

and your code provide this:
image

**Comment by lukascernydis** [comment]
```
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager', [
        'bundles' => false,
        'getBundle' => function ($name) {
            if (!class_exists($name)) {
                $name = 'yii\web\AssetBundle';
            }

            return Yii::createObject($name);
        },
        'publish' => function () {
            return [null, null];
        },
    ]));
}
```

**Comment by githubjeka** [comment]
Like as https://github.com/Codeception/Codeception/pull/3387#issuecomment-259410202

Result - https://github.com/Codeception/Codeception/pull/3719#issuecomment-260119962

To fix you should create AssetManagerInterface and use his implement in your tests. No in a tool for tests.
Creating `@webroot` directory not issue of Codeception, it issue of Yii2. And should be fix in framework, otherwise in your code. Like as now via config.

**Comment by lukascernydis** [comment]
It is not possible to override AssetManager trough Yii config when mockAssetManager() replaces it with yii\web\AssetManager again.

We should respect AssetManager class set in config. So the mock will look like:

```
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make(get_class($this->app->getAssetManager()), ['bundles' => false]));
}
```

**Comment by githubjeka** [comment]
That why appeared [this PR](https://github.com/Codeception/Codeception/pull/3742)

Users should get to options between confrig or mock in his application. By default it's config option.

**Comment by lukascernydis** [comment]
#3742 sounds good.

Thank you for patience.

**Comment by githubjeka** [comment]
Thank you too.

**Pull request merged**
