### PR TITLE
Support LIKE operator in Db Module

### PR DESCRIPTION
**Pull request by teeencho**
Adding the ability to generate where clause with LIKE operator usage ['field LIKE' => '%value%']

### CODE REVIEW

**Comment by Naktibalda** [comment]
What's your use case?
In tests you should know exactly what data is present in database before test and what record should be added by the application you are testing.

**Comment by teeencho** [comment]
@Naktibalda Hi, we have a table where we store tasks to be executed in the background. The field is in JSON format. I couldn't possibly know the exact parameter values, since some are generated by my test and some are tokens generated by an external payment service.

**Comment by Naktibalda** [comment]
Looks valid.

@DavertMik are you happy with the syntax?

**Comment by DavertMik** [comment]
I like the syntax but docs should be updated to mention this. 
Could you update Db module docblock? (.md docs are generated form it)

**Comment by Naktibalda** [comment]
I will update the docblock.

**Comment by Naktibalda** [comment]
@DavertMik I am confused.
How did you add Example to http://codeception.com/docs/modules/Db#seeInDatabase ?
seeInDatabase has no docblock https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Db.php#L325

**Comment by DavertMik** [comment]
Ok, looks like I added this from `DbInterface` from https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Interfaces/Db.php

**Pull request merged**
