### PR TITLE
Release 2.2.11

### PR DESCRIPTION
**Pull request by DavertMik**
* updated changelog
* lowered PHPUnit support back to 5.x to avoid potential issues in patch release. Will be enabled back in 2.3.0

### CODE REVIEW

**Comment by Faryshta** [comment]
can we include #4208 ? this bug fix is needed for yii2 `cleanup` config to work when dealing with fixtures

**Comment by DavertMik** [comment]
@Faryshta yes, it will be included

**Comment by Faryshta** [comment]
:balloon: :grinning: :1st_place_medal:

**Comment by KacerCZ** [comment]
Hi, Codeception 2.3.0 has still restriction on PHPUnit version lower than 6.0.

**Pull request merged**
