### PR TITLE
Dot notation for params replacement. Fixes #3339

### LINKED ISSUE #3339: Parameters token replacement with complex structure
Given `settings.yml` containing

```
api:
  db:
    host: 127.0.0.1
    database: db
    username: user
    password: pass
```

and `codeception.yml` containing

```
params:
  - settings.yml
```

I want `acceptance.yml` parameters replacement

```
modules:
  enabled:
    - Db:
        dsn: 'mysql:host=%api.db.host%;dbname=%api.db.database%'
        user: '%api.db.username%'
        password: '%api.db.password%'
```

resulting in

```
modules:
  enabled:
    - Db:
        dsn: 'mysql:host=127.0.0.1;dbname=db'
        user: user
        password: pass
```

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by neoascetic** [comment]
@Naktibalda it fails anyways

**Comment by Naktibalda** [comment]
But it fails for a different reason.

@samdark @DavertMik  yii-basic-app no longer works on PHP 5.4 and 5.5
and it fails on 5.6 and 7.0 with 

```
$ php codecept build -c frameworks-yii-basic/tests
  [Codeception\Exception\ConfigurationException]                            

  Your configuration file `frameworks-yii-basic/tests` could not be found.
```

**Comment by Naktibalda** [comment]
Please rebase one more time:

```
git fetch upstream 2.2:2.2
git rebase 2.2 complex-params-replacing
git push -f
```

**Comment by neoascetic** [comment]
Any comments?

**Pull request merged**
